############  PROPERTIES TO BE CHANGED  !!!!
# SETTINGS To acces ePims datastore
spring.datasource.url= jdbc:postgresql://<epims_db_host>:5432/<ePims_DB>
spring.datasource.username= <db_pims_user>
spring.datasource.password= <db_pims_pwd>

# ePims paths
# epims.repository path to root of epims repository   /path/epims/data/repository
# epims.ftp.home path to entry point for FTP server
epims.repository=<PATH_PIMS_REPO>
epims.ftp.home=<PATH_PIMS_FTP>

#configure JWT secret key. Mandatory to connect to server
jwt.secret=<A UNIQUE KEY>
############  PROPERTIES TO BE CHANGED  END

spring.datasource.driver-class-name=org.postgresql.Driver
# SETTINGS FOR POSTGRES 8.4.7
# CONFIGURATION of Hibernate : version must also be changed to 5.2.9.Final in pom.xml
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQL82Dialect

# SETTINGS FOR POSTGRES 9.6.11
# CONFIGURATION of Hibernate : version must also be changed to 5.6.5.Final in pom.xml
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
# Spring Error Controller config. VDS needed ?
server.error.path="/error"

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update
#spring.jpa.show-sql=true

# Spring activeMQ config. Adapt to local installation
spring.activemq.user=admin
spring.activemq.password=admin
spring.activemq.broker-url=tcp://0.0.0.0:61617?jms.redeliveryPolicy.maximumRedeliveries=1
# allow jms topics
spring.jms.pub-sub-domain=true
management.endpoints.web.exposure.include=beans

# logging
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.bean=DEBUG
logging.level.org.springframework.boot=DEBUG
logging.level.fr.edyp=DEBUG
logging.level.org.hibernate=ERROR
logging.file.name=ePimsServer.log


# HikariCP settings
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
# 10 minutes
spring.datasource.hikari.idle-timeout=600000
# 30 minutes
spring.datasource.hikari.max-lifetime=1800000
# 30 seconds
spring.datasource.hikari.connection-timeout=30000
# 5 seconds
spring.datasource.hikari.validation-timeout=5000
# 60 seconds (optional)
spring.datasource.hikari.leak-detection-threshold=60000

# Optional: Connection validation (useful if connections get closed unexpectedly)
spring.datasource.hikari.connection-test-query=SELECT 1
