#FilePreferences
#Thu Jun 09 11:34:28 CEST 2022
#PATH used by ePIMS
PIMS_ROOT=<PATH_TO_ROOT>
PIMS_SYSTEM_RELATIVE_PATH=system
REPOSITORY_DEFAULT_ABC_LETTER=b
ARCHIVE_ROOT=<PATH_TO_ARCHIVE_ROOT>
#FTP Login information
FTP_LOG=<PIMS_FTP_USER>
FTP_PASSWORD=<PIMS_FTP_PWD>
FTP_HOST=<PIMS_FTP_HOST>
# Use local jms server... Do not change
JMS_HOST=tcp\://0.0.0.0\:61617?jms.redeliveryPolicy.maximumRedeliveries\=1


