package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import jakarta.persistence.*;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import fr.edyp.epims.json.Category;

/**
 * Acquisition generated by hbm2java
 */
@Entity
@Table(name = "acquisition", schema = "public")
public class Acquisition implements java.io.Serializable {

	private int id;
	private ProtocolApplication protocolApplication;
	private Spectrometer spectrometer;
	private String nature;
	private Float durationMin;
	private String methodName;
	private Float injectionVolume;
	private String vialInformation;
	private Category category;

	public Acquisition() {
	}

	public Acquisition(ProtocolApplication protocolApplication, Spectrometer spectrometer, String nature) {
		this.protocolApplication = protocolApplication;
		this.spectrometer = spectrometer;
		this.nature = nature;
	}

	public Acquisition(ProtocolApplication protocolApplication, Spectrometer spectrometer, String nature,
					   Float durationMin) {
		this.protocolApplication = protocolApplication;
		this.spectrometer = spectrometer;
		this.nature = nature;
		this.durationMin = durationMin;
	}

	public Acquisition(ProtocolApplication protocolApplication, Spectrometer spectrometer, String nature,
					   Float durationMin, String methodName, Float injectionVolume, String vialInformation) {
		this.protocolApplication = protocolApplication;
		this.spectrometer = spectrometer;
		this.nature = nature;
		this.durationMin = durationMin;
		this.methodName = methodName;
		this.injectionVolume = injectionVolume;
		this.vialInformation = vialInformation;
	}


	@GenericGenerator(name = "org.o7planning.generateentities.AcquisitionIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "protocolApplication"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.AcquisitionIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public ProtocolApplication getProtocolApplication() {
		return this.protocolApplication;
	}

	public void setProtocolApplication(ProtocolApplication protocolApplication) {
		this.protocolApplication = protocolApplication;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "spectrometer", nullable = false)
	public Spectrometer getSpectrometer() {
		return this.spectrometer;
	}

	public void setSpectrometer(Spectrometer spectrometer) {
		this.spectrometer = spectrometer;
	}

	@Column(name = "nature", nullable = false)
	public String getNature() {
		return this.nature;
	}

	public void setNature(String nature) {
		this.nature = nature;
	}

	@Column(name = "duration_min")
	public Float getDurationMin() {
		return this.durationMin;
	}

	public void setDurationMin(Float durationMin) {
		this.durationMin = durationMin;
	}

	@Column(name = "method_name")
	public String getMethodName() {
		return methodName;
	}

	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

	@Column(name = "injection_volume")
	public Float getInjectionVolume() {
		return injectionVolume;
	}

	public void setInjectionVolume(Float injectionVolume) {
		this.injectionVolume = injectionVolume;
	}

	@Column(name = "vial_information")
	public String getVialInformation() {
		return vialInformation;
	}

	public void setVialInformation(String vialInformation) {
		this.vialInformation = vialInformation;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "category", nullable = false)
	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

}
