package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AcquisitionProtocolApplication generated by hbm2java
 */
@Entity
@Table(name = "acquisition_protocol_application", schema = "public")
public class AcquisitionProtocolApplication implements java.io.Serializable {

	private AcquisitionProtocolApplicationId id;

	public AcquisitionProtocolApplication() {
	}

	public AcquisitionProtocolApplication(AcquisitionProtocolApplicationId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "name", column = @Column(name = "name", length = 50)),
			@AttributeOverride(name = "date", column = @Column(name = "date")),
			@AttributeOverride(name = "actor", column = @Column(name = "actor")),
			@AttributeOverride(name = "comment", column = @Column(name = "comment")),
			@AttributeOverride(name = "protocol", column = @Column(name = "protocol")),
			@AttributeOverride(name = "spectrometer", column = @Column(name = "spectrometer")),
			@AttributeOverride(name = "nature", column = @Column(name = "nature")),
			@AttributeOverride(name = "durationMin", column = @Column(name = "duration_min")) })
	public AcquisitionProtocolApplicationId getId() {
		return this.id;
	}

	public void setId(AcquisitionProtocolApplicationId id) {
		this.id = id;
	}

}
