package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Acquisition generated by hbm2java
 */
@Entity
@Table(name = "acquisition", schema = "public")
public class Acquisition implements java.io.Serializable {

	private int id;
	private ProtocolApplication protocolApplication;
	private Spectrometer spectrometer;
	private String nature;
	private Float durationMin;

	public Acquisition() {
	}

	public Acquisition(ProtocolApplication protocolApplication, Spectrometer spectrometer, String nature) {
		this.protocolApplication = protocolApplication;
		this.spectrometer = spectrometer;
		this.nature = nature;
	}

	public Acquisition(ProtocolApplication protocolApplication, Spectrometer spectrometer, String nature,
					   Float durationMin) {
		this.protocolApplication = protocolApplication;
		this.spectrometer = spectrometer;
		this.nature = nature;
		this.durationMin = durationMin;
	}


	@GenericGenerator(name = "org.o7planning.generateentities.AcquisitionIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "protocolApplication"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.AcquisitionIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public ProtocolApplication getProtocolApplication() {
		return this.protocolApplication;
	}

	public void setProtocolApplication(ProtocolApplication protocolApplication) {
		this.protocolApplication = protocolApplication;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "spectrometer", nullable = false)
	public Spectrometer getSpectrometer() {
		return this.spectrometer;
	}

	public void setSpectrometer(Spectrometer spectrometer) {
		this.spectrometer = spectrometer;
	}

	@Column(name = "nature", nullable = false)
	public String getNature() {
		return this.nature;
	}

	public void setNature(String nature) {
		this.nature = nature;
	}

	@Column(name = "duration_min")
	public Float getDurationMin() {
		return this.durationMin;
	}

	public void setDurationMin(Float durationMin) {
		this.durationMin = durationMin;
	}

}
