package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * AcquisitionProtocol generated by hbm2java
 */
@Entity
@Table(name = "acquisition_protocol", schema = "public")
public class AcquisitionProtocol implements java.io.Serializable {

	private int id;
	private Protocol protocol;
	private String softwareVersion;
	private String softwareName;
	private String parametersFile;

	public AcquisitionProtocol() {
	}

	public AcquisitionProtocol(Protocol protocol) {
		this.protocol = protocol;
	}

	public AcquisitionProtocol(Protocol protocol, String softwareVersion, String softwareName,
			String parametersFile) {
		this.protocol = protocol;
		this.softwareVersion = softwareVersion;
		this.softwareName = softwareName;
		this.parametersFile = parametersFile;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.AcquisitionProtocolIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "protocol"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.AcquisitionProtocolIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Protocol getProtocol() {
		return this.protocol;
	}

	public void setProtocol(Protocol protocol) {
		this.protocol = protocol;
	}

	@Column(name = "software_version")
	public String getSoftwareVersion() {
		return this.softwareVersion;
	}

	public void setSoftwareVersion(String softwareVersion) {
		this.softwareVersion = softwareVersion;
	}

	@Column(name = "software_name")
	public String getSoftwareName() {
		return this.softwareName;
	}

	public void setSoftwareName(String softwareName) {
		this.softwareName = softwareName;
	}

	@Column(name = "parameters_file")
	public String getParametersFile() {
		return this.parametersFile;
	}

	public void setParametersFile(String parametersFile) {
		this.parametersFile = parametersFile;
	}

}
