package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * ActorRole generated by hbm2java
 */
@Entity
@Table(name = "actor_role", schema = "public")
public class ActorRole implements java.io.Serializable {

	private ActorRoleId id;
	private Actor actor;

	public ActorRole() {
	}

	public ActorRole(ActorRoleId id, Actor actor) {
		this.id = id;
		this.actor = actor;
	}

	@EmbeddedId
	public ActorRoleId getId() {
		return this.id;
	}

	public void setId(ActorRoleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "login", nullable = false, insertable = false, updatable = false)
	public Actor getActor() {
		return this.actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

}
