package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActorRoleId generated by hbm2java
 */
@Embeddable
public class ActorRoleId implements java.io.Serializable {

	private String login;
	private String role;

	public ActorRoleId() {
	}

	public ActorRoleId(String login, String role) {
		this.login = login;
		this.role = role;
	}

	@Column(name = "login", nullable = false)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "role", nullable = false, length = 15)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActorRoleId))
			return false;
		ActorRoleId castOther = (ActorRoleId) other;

		return ((this.getLogin() == castOther.getLogin()) || (this.getLogin() != null && castOther.getLogin() != null
				&& this.getLogin().equals(castOther.getLogin())))
				&& ((this.getRole() == castOther.getRole()) || (this.getRole() != null && castOther.getRole() != null
						&& this.getRole().equals(castOther.getRole())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLogin() == null ? 0 : this.getLogin()).hashCode();
		result = 37 * result + (getRole() == null ? 0 : this.getRole().hashCode());
		return result;
	}

}
