package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AdminInfos generated by hbm2java
 */
@Entity
@Table(name = "admin_infos", schema = "public")
public class AdminInfos implements java.io.Serializable {

	private String modelVersion;
	private String creationDate;
	private String updateDate;

	public AdminInfos() {
	}

	public AdminInfos(String modelVersion) {
		this.modelVersion = modelVersion;
	}

	public AdminInfos(String modelVersion, String creationDate, String updateDate) {
		this.modelVersion = modelVersion;
		this.creationDate = creationDate;
		this.updateDate = updateDate;
	}

	@Id

	@Column(name = "model_version", unique = true, nullable = false)
	public String getModelVersion() {
		return this.modelVersion;
	}

	public void setModelVersion(String modelVersion) {
		this.modelVersion = modelVersion;
	}

	@Column(name = "creation_date")
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "update_date")
	public String getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

}
