package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BandLocator generated by hbm2java
 */
@Entity
@Table(name = "band_locator", schema = "public")
public class BandLocator implements java.io.Serializable {

	private BandLocatorId id;

	public BandLocator() {
	}

	public BandLocator(BandLocatorId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "sample", column = @Column(name = "sample")),
			@AttributeOverride(name = "separationResult", column = @Column(name = "separation_result")),
			@AttributeOverride(name = "experimentalMass", column = @Column(name = "experimental_mass")) })
	public BandLocatorId getId() {
		return this.id;
	}

	public void setId(BandLocatorId id) {
		this.id = id;
	}

}
