package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Band generated by hbm2java
 */
@Entity
@Table(name = "band", schema = "public")
public class Band implements java.io.Serializable {

	private int id;
	private SampleLocator sampleLocator;
	private String experimentalMass;

	public Band() {
	}

	public Band(SampleLocator sampleLocator) {
		this.sampleLocator = sampleLocator;
	}

	public Band(SampleLocator sampleLocator, String experimentalMass) {
		this.sampleLocator = sampleLocator;
		this.experimentalMass = experimentalMass;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.BandIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "sampleLocator"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.BandIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public SampleLocator getSampleLocator() {
		return this.sampleLocator;
	}

	public void setSampleLocator(SampleLocator sampleLocator) {
		this.sampleLocator = sampleLocator;
	}

	@Column(name = "experimental_mass")
	public String getExperimentalMass() {
		return this.experimentalMass;
	}

	public void setExperimentalMass(String experimentalMass) {
		this.experimentalMass = experimentalMass;
	}

}
