package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * BiologicOrigin generated by hbm2java
 */
@Entity
@Table(name = "biologic_origin", schema = "public")
public class BiologicOrigin implements java.io.Serializable {

	private int id;
	private SampleKind sampleKind;
	private SampleSpecies sampleSpecies;
	private SampleSubcellularLocalisation sampleSubcellularLocalisation;
	private SampleType sampleType;
	private String commentOrigin;
	private Set<Sample> samples = new HashSet<Sample>(0);

	public BiologicOrigin() {
	}

	public BiologicOrigin(int id, SampleSpecies sampleSpecies) {
		this.id = id;
		this.sampleSpecies = sampleSpecies;
	}

	public BiologicOrigin(SampleKind sampleKind, SampleSpecies sampleSpecies,
						  SampleSubcellularLocalisation sampleSubcellularLocalisation, SampleType sampleType,
						  String commentOrigin) {
		this.sampleKind = sampleKind;
		this.sampleSpecies = sampleSpecies;
		this.sampleSubcellularLocalisation = sampleSubcellularLocalisation;
		this.sampleType = sampleType;
		this.commentOrigin = commentOrigin;
		this.samples = null;
	}

	public BiologicOrigin(int id, SampleKind sampleKind, SampleSpecies sampleSpecies,
			SampleSubcellularLocalisation sampleSubcellularLocalisation, SampleType sampleType,
			String commentOrigin, Set<Sample> samples) {
		this.id = id;
		this.sampleKind = sampleKind;
		this.sampleSpecies = sampleSpecies;
		this.sampleSubcellularLocalisation = sampleSubcellularLocalisation;
		this.sampleType = sampleType;
		this.commentOrigin = commentOrigin;
		this.samples = samples;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "biologic_origin_generator")
	@SequenceGenerator(name = "biologic_origin_generator", sequenceName = "biologic_origin_id_seq", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sample_kind")
	public SampleKind getSampleKind() {
		return this.sampleKind;
	}

	public void setSampleKind(SampleKind sampleKind) {
		this.sampleKind = sampleKind;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sample_species", nullable = false)
	public SampleSpecies getSampleSpecies() {
		return this.sampleSpecies;
	}

	public void setSampleSpecies(SampleSpecies sampleSpecies) {
		this.sampleSpecies = sampleSpecies;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sample_subcellular_localisation")
	public SampleSubcellularLocalisation getSampleSubcellularLocalisation() {
		return this.sampleSubcellularLocalisation;
	}

	public void setSampleSubcellularLocalisation(SampleSubcellularLocalisation sampleSubcellularLocalisation) {
		this.sampleSubcellularLocalisation = sampleSubcellularLocalisation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sample_type")
	public SampleType getSampleType() {
		return this.sampleType;
	}

	public void setSampleType(SampleType sampleType) {
		this.sampleType = sampleType;
	}

	@Column(name = "comment_origin")
	public String getCommentOrigin() {
		return this.commentOrigin;
	}

	public void setCommentOrigin(String commentOrigin) {
		this.commentOrigin = commentOrigin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "biologicOrigin")
	public Set<Sample> getSamples() {
		return this.samples;
	}

	public void setSamples(Set<Sample> samples) {
		this.samples = samples;
	}

}
