package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CentrifugationProtocolApplication generated by hbm2java
 */
@Entity
@Table(name = "centrifugation_protocol_application", schema = "public")
public class CentrifugationProtocolApplication implements java.io.Serializable {

	private CentrifugationProtocolApplicationId id;

	public CentrifugationProtocolApplication() {
	}

	public CentrifugationProtocolApplication(CentrifugationProtocolApplicationId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "name", column = @Column(name = "name", length = 50)),
			@AttributeOverride(name = "date", column = @Column(name = "date")),
			@AttributeOverride(name = "actor", column = @Column(name = "actor")),
			@AttributeOverride(name = "comment", column = @Column(name = "comment")),
			@AttributeOverride(name = "protocol", column = @Column(name = "protocol")),
			@AttributeOverride(name = "result", column = @Column(name = "result")),
			@AttributeOverride(name = "rpm", column = @Column(name = "rpm")),
			@AttributeOverride(name = "matrixSupport", column = @Column(name = "matrix_support")) })
	public CentrifugationProtocolApplicationId getId() {
		return this.id;
	}

	public void setId(CentrifugationProtocolApplicationId id) {
		this.id = id;
	}

}
