package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Centrifugation generated by hbm2java
 */
@Entity
@Table(name = "centrifugation", schema = "public")
public class Centrifugation implements java.io.Serializable {

	private int id;
	private Separation separation;
	private Integer rpm;
	private String matrixSupport;

	public Centrifugation() {
	}

	public Centrifugation(Separation separation) {
		this.separation = separation;
	}

	public Centrifugation(Separation separation, Integer rpm, String matrixSupport) {
		this.separation = separation;
		this.rpm = rpm;
		this.matrixSupport = matrixSupport;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.CentrifugationIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "separation"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.CentrifugationIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Separation getSeparation() {
		return this.separation;
	}

	public void setSeparation(Separation separation) {
		this.separation = separation;
	}

	@Column(name = "rpm")
	public Integer getRpm() {
		return this.rpm;
	}

	public void setRpm(Integer rpm) {
		this.rpm = rpm;
	}

	@Column(name = "matrix_support")
	public String getMatrixSupport() {
		return this.matrixSupport;
	}

	public void setMatrixSupport(String matrixSupport) {
		this.matrixSupport = matrixSupport;
	}

}
