package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ChemicalFraction generated by hbm2java
 */
@Entity
@Table(name = "chemical_fraction", schema = "public")
public class ChemicalFraction implements java.io.Serializable {

	private int id;
	private SampleLocator sampleLocator;
	private Integer number;

	public ChemicalFraction() {
	}

	public ChemicalFraction(SampleLocator sampleLocator) {
		this.sampleLocator = sampleLocator;
	}

	public ChemicalFraction(SampleLocator sampleLocator, Integer number) {
		this.sampleLocator = sampleLocator;
		this.number = number;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.ChemicalFractionIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "sampleLocator"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.ChemicalFractionIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public SampleLocator getSampleLocator() {
		return this.sampleLocator;
	}

	public void setSampleLocator(SampleLocator sampleLocator) {
		this.sampleLocator = sampleLocator;
	}

	@Column(name = "number")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

}
