package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "company", schema = "public")
public class Company implements java.io.Serializable {

	private String name;
	private String manager;
	private String address;
	private String postalCode;
	private Set<Contact> contacts = new HashSet<Contact>(0);

	public Company() {
	}

	public Company(String name) {
		this.name = name;
	}

	public Company(String name, String manager, String address, String postalCode,
			Set<Contact> contacts) {
		this.name = name;
		this.manager = manager;
		this.address = address;
		this.postalCode = postalCode;
		this.contacts = contacts;
	}

	@Id
	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "manager")
	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "postal_code")
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

}
