package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "contact", schema = "public")
public class Contact implements java.io.Serializable {

	private int id;
	private Company company;
	private String lastName;
	private String firstName;
	private String telephoneNumber;
	private String faxNumber;
	private String email;
	private Set<ProjContacts> projContactses = new HashSet<ProjContacts>(0);
	private Set<StudyContacts> studyContactses = new HashSet<StudyContacts>(0);
	private Set<ProgContacts> progContactses = new HashSet<ProgContacts>(0);
	private Set<Actor> actors = new HashSet<Actor>(0);

	public Contact() {
	}

	public Contact(int id, String lastName, String firstName) {
		this.id = id;
		this.lastName = lastName;
		this.firstName = firstName;
	}

	public Contact(Company company, String lastName, String firstName, String telephoneNumber,
				   String faxNumber, String email, Set<ProjContacts> projContactses,
				   Set<StudyContacts> studyContactses, Set<ProgContacts> progContactses, Set<Actor> actors) {
		this.company = company;
		this.lastName = lastName;
		this.firstName = firstName;
		this.telephoneNumber = telephoneNumber;
		this.faxNumber = faxNumber;
		this.email = email;
		this.projContactses = projContactses;
		this.studyContactses = studyContactses;
		this.progContactses = progContactses;
		this.actors = actors;
	}

	public Contact(int id, Company company, String lastName, String firstName, String telephoneNumber,
				   String faxNumber, String email, Set<ProjContacts> projContactses,
			Set<StudyContacts> studyContactses, Set<ProgContacts> progContactses, Set<Actor> actors) {
		this.id = id;
		this.company = company;
		this.lastName = lastName;
		this.firstName = firstName;
		this.telephoneNumber = telephoneNumber;
		this.faxNumber = faxNumber;
		this.email = email;
		this.projContactses = projContactses;
		this.studyContactses = studyContactses;
		this.progContactses = progContactses;
		this.actors = actors;
	}

	public Contact(Company company, String lastName, String firstName, String telephoneNumber,
				   String faxNumber, String email) {
		this.company = company;
		this.lastName = lastName;
		this.firstName = firstName;
		this.telephoneNumber = telephoneNumber;
		this.faxNumber = faxNumber;
		this.email = email;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "contact_generator")
	@SequenceGenerator(name = "contact_generator", sequenceName = "contact_id_seq", allocationSize = 1)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "last_name", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "first_name", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "telephone_number")
	public String getTelephoneNumber() {
		return this.telephoneNumber;
	}

	public void setTelephoneNumber(String telephoneNumber) {
		this.telephoneNumber = telephoneNumber;
	}

	@Column(name = "fax_number")
	public String getFaxNumber() {
		return this.faxNumber;
	}

	public void setFaxNumber(String faxNumber) {
		this.faxNumber = faxNumber;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contact")
	public Set<ProjContacts> getProjContactses() {
		return this.projContactses;
	}

	public void setProjContactses(Set<ProjContacts> projContactses) {
		this.projContactses = projContactses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contact")
	public Set<StudyContacts> getStudyContactses() {
		return this.studyContactses;
	}

	public void setStudyContactses(Set<StudyContacts> studyContactses) {
		this.studyContactses = studyContactses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contact")
	public Set<ProgContacts> getProgContactses() {
		return this.progContactses;
	}

	public void setProgContactses(Set<ProgContacts> progContactses) {
		this.progContactses = progContactses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contact")
	public Set<Actor> getActors() {
		return this.actors;
	}

	public void setActors(Set<Actor> actors) {
		this.actors = actors;
	}

}
