package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocumentReferenceId generated by hbm2java
 */
@Embeddable
public class DocumentReferenceId implements java.io.Serializable {

	private Integer id;
	private String documentRef;
	private String part;

	public DocumentReferenceId() {
	}

	public DocumentReferenceId(Integer id, String documentRef, String part) {
		this.id = id;
		this.documentRef = documentRef;
		this.part = part;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "document_ref")
	public String getDocumentRef() {
		return this.documentRef;
	}

	public void setDocumentRef(String documentRef) {
		this.documentRef = documentRef;
	}

	@Column(name = "part", length = 50)
	public String getPart() {
		return this.part;
	}

	public void setPart(String part) {
		this.part = part;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentReferenceId))
			return false;
		DocumentReferenceId castOther = (DocumentReferenceId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getDocumentRef() == castOther.getDocumentRef())
						|| (this.getDocumentRef() != null && castOther.getDocumentRef() != null
								&& this.getDocumentRef().equals(castOther.getDocumentRef())))
				&& ((this.getPart() == castOther.getPart()) || (this.getPart() != null && castOther.getPart() != null
						&& this.getPart().equals(castOther.getPart())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getDocumentRef() == null ? 0 : this.getDocumentRef().hashCode());
		result = 37 * result + (getPart() == null ? 0 : this.getPart().hashCode());
		return result;
	}

}
