package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Document generated by hbm2java
 */
@Entity
@Table(name = "document", schema = "public")
public class Document implements java.io.Serializable {

	private int id;
	private Reference reference;
	private String documentRef;
	private String part;

	public Document() {
	}

	public Document(Reference reference, String documentRef) {
		this.reference = reference;
		this.documentRef = documentRef;
	}

	public Document(Reference reference, String documentRef, String part) {
		this.reference = reference;
		this.documentRef = documentRef;
		this.part = part;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.DocumentIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "reference"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.DocumentIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Reference getReference() {
		return this.reference;
	}

	public void setReference(Reference reference) {
		this.reference = reference;
	}

	@Column(name = "document_ref", nullable = false)
	public String getDocumentRef() {
		return this.documentRef;
	}

	public void setDocumentRef(String documentRef) {
		this.documentRef = documentRef;
	}

	@Column(name = "part", length = 50)
	public String getPart() {
		return this.part;
	}

	public void setPart(String part) {
		this.part = part;
	}

}
