package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FileTagsId generated by hbm2java
 */
@Embeddable
public class FileTagsId implements java.io.Serializable {

	private int file;
	private String tag;

	public FileTagsId() {
	}

	public FileTagsId(int file, String tag) {
		this.file = file;
		this.tag = tag;
	}

	@Column(name = "file", nullable = false)
	public int getFile() {
		return this.file;
	}

	public void setFile(int file) {
		this.file = file;
	}

	@Column(name = "tag", nullable = false)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FileTagsId))
			return false;
		FileTagsId castOther = (FileTagsId) other;

		return (this.getFile() == castOther.getFile()) && ((this.getTag() == castOther.getTag())
				|| (this.getTag() != null && castOther.getTag() != null && this.getTag().equals(castOther.getTag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFile();
		result = 37 * result + (getTag() == null ? 0 : this.getTag().hashCode());
		return result;
	}

}
