package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.*;

/**
 * FileLink generated by hbm2java
 */
@Entity
@Table(name = "file_link", schema = "public")
@DiscriminatorColumn(name="associated_entity",
		discriminatorType = DiscriminatorType.STRING)
public class FileLink implements java.io.Serializable {

	private int id;
	private AttachedFile attachedFile;
	private Integer idFk;
	private String nameFk;
	private String associatedEntity;

	public FileLink() {
	}

	public FileLink( AttachedFile attachedFile) {
		this.attachedFile = attachedFile;
	}

	public FileLink(int id, AttachedFile attachedFile, String associatedEntity) {
		this.id = id;
		this.attachedFile = attachedFile;
		this.associatedEntity = associatedEntity;
	}

	public FileLink(int id, AttachedFile attachedFile, Integer idFk, String nameFk
			, String associatedEntity) {
		this.id = id;
		this.attachedFile = attachedFile;
		this.idFk = idFk;
		this.nameFk = nameFk;
		this.associatedEntity = associatedEntity;
	}

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE, generator = "file_link_generator")
	@SequenceGenerator(name = "file_link_generator", sequenceName = "file_link_id_seq", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attached_file", nullable = false)
	public AttachedFile getAttachedFile() {
		return this.attachedFile;
	}

	public void setAttachedFile(AttachedFile attachedFile) {
		this.attachedFile = attachedFile;
	}


	@Column(name = "id_fk")
	public Integer getIdFk() {
		return this.idFk;
	}

	public void setIdFk(Integer idFk) {
		this.idFk = idFk;
	}

	@Column(name = "name_fk")
	public String getNameFk() {
		return this.nameFk;
	}

	public void setNameFk(String nameFk) {
		this.nameFk = nameFk;
	}


	@Column(name = "associated_entity", nullable = false, insertable = false, updatable = false)
	public String getAssociatedEntity() {
		return this.associatedEntity;
	}

	public void setAssociatedEntity(String associatedEntity) {
		this.associatedEntity = associatedEntity;
	}

}
