package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Gel1d generated by hbm2java
 */
@Entity
@Table(name = "gel_1d", schema = "public")
public class Gel1d implements java.io.Serializable {

	private int id;
	private String picture;
	private Set<Lane> lanes = new HashSet<Lane>(0);

	public Gel1d() {
	}

	public Gel1d(int id) {
		this.id = id;
	}

	public Gel1d(int id, String picture, Set<Lane> lanes) {
		this.id = id;
		this.picture = picture;
		this.lanes = lanes;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "picture")
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gel1d")
	public Set<Lane> getLanes() {
		return this.lanes;
	}

	public void setLanes(Set<Lane> lanes) {
		this.lanes = lanes;
	}

}
