package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Gel1dMigration generated by hbm2java
 */
@Entity
@Table(name = "gel_1d_migration", schema = "public")
public class Gel1dMigration implements java.io.Serializable {

	private int id;
	private GelMigration gelMigration;

	public Gel1dMigration() {
	}

	public Gel1dMigration(GelMigration gelMigration) {
		this.gelMigration = gelMigration;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.Gel1dMigrationIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "gelMigration"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.Gel1dMigrationIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public GelMigration getGelMigration() {
		return this.gelMigration;
	}

	public void setGelMigration(GelMigration gelMigration) {
		this.gelMigration = gelMigration;
	}

}
