package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Gel1dMigrationProtocolApplicationId generated by hbm2java
 */
@Embeddable
public class Gel1dMigrationProtocolApplicationId implements java.io.Serializable {

	private Integer id;
	private String name;
	private String date;
	private String actor;
	private String comment;
	private Integer protocol;
	private Integer result;
	private String massStart;
	private String massEnd;
	private String denaturingAgent;

	public Gel1dMigrationProtocolApplicationId() {
	}

	public Gel1dMigrationProtocolApplicationId(Integer id, String name, String date, String actor,
			String comment, Integer protocol, Integer result, String massStart, String massEnd,
			String denaturingAgent) {
		this.id = id;
		this.name = name;
		this.date = date;
		this.actor = actor;
		this.comment = comment;
		this.protocol = protocol;
		this.result = result;
		this.massStart = massStart;
		this.massEnd = massEnd;
		this.denaturingAgent = denaturingAgent;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "date")
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "actor")
	public String getActor() {
		return this.actor;
	}

	public void setActor(String actor) {
		this.actor = actor;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "protocol")
	public Integer getProtocol() {
		return this.protocol;
	}

	public void setProtocol(Integer protocol) {
		this.protocol = protocol;
	}

	@Column(name = "result")
	public Integer getResult() {
		return this.result;
	}

	public void setResult(Integer result) {
		this.result = result;
	}

	@Column(name = "mass_start")
	public String getMassStart() {
		return this.massStart;
	}

	public void setMassStart(String massStart) {
		this.massStart = massStart;
	}

	@Column(name = "mass_end")
	public String getMassEnd() {
		return this.massEnd;
	}

	public void setMassEnd(String massEnd) {
		this.massEnd = massEnd;
	}

	@Column(name = "denaturing_agent")
	public String getDenaturingAgent() {
		return this.denaturingAgent;
	}

	public void setDenaturingAgent(String denaturingAgent) {
		this.denaturingAgent = denaturingAgent;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Gel1dMigrationProtocolApplicationId))
			return false;
		Gel1dMigrationProtocolApplicationId castOther = (Gel1dMigrationProtocolApplicationId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())))
				&& ((this.getActor() == castOther.getActor()) || (this.getActor() != null
						&& castOther.getActor() != null && this.getActor().equals(castOther.getActor())))
				&& ((this.getComment() == castOther.getComment()) || (this.getComment() != null
						&& castOther.getComment() != null && this.getComment().equals(castOther.getComment())))
				&& ((this.getProtocol() == castOther.getProtocol()) || (this.getProtocol() != null
						&& castOther.getProtocol() != null && this.getProtocol().equals(castOther.getProtocol())))
				&& ((this.getResult() == castOther.getResult()) || (this.getResult() != null
						&& castOther.getResult() != null && this.getResult().equals(castOther.getResult())))
				&& ((this.getMassStart() == castOther.getMassStart()) || (this.getMassStart() != null
						&& castOther.getMassStart() != null && this.getMassStart().equals(castOther.getMassStart())))
				&& ((this.getMassEnd() == castOther.getMassEnd()) || (this.getMassEnd() != null
						&& castOther.getMassEnd() != null && this.getMassEnd().equals(castOther.getMassEnd())))
				&& ((this.getDenaturingAgent() == castOther.getDenaturingAgent())
						|| (this.getDenaturingAgent() != null && castOther.getDenaturingAgent() != null
								&& this.getDenaturingAgent().equals(castOther.getDenaturingAgent())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getActor() == null ? 0 : this.getActor().hashCode());
		result = 37 * result + (getComment() == null ? 0 : this.getComment().hashCode());
		result = 37 * result + (getProtocol() == null ? 0 : this.getProtocol().hashCode());
		result = 37 * result + (getResult() == null ? 0 : this.getResult().hashCode());
		result = 37 * result + (getMassStart() == null ? 0 : this.getMassStart().hashCode());
		result = 37 * result + (getMassEnd() == null ? 0 : this.getMassEnd().hashCode());
		result = 37 * result + (getDenaturingAgent() == null ? 0 : this.getDenaturingAgent().hashCode());
		return result;
	}

}
