package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Gel2d generated by hbm2java
 */
@Entity
@Table(name = "gel_2d", schema = "public")
public class Gel2d implements java.io.Serializable {

	private int id;
	private SeparationResult separationResult;
	private String picture;
	private String firstDimensionDetails;
	private String secondDimensionDetails;

	public Gel2d() {
	}

	public Gel2d(SeparationResult separationResult) {
		this.separationResult = separationResult;
	}

	public Gel2d(SeparationResult separationResult, String picture, String firstDimensionDetails,
			String secondDimensionDetails) {
		this.separationResult = separationResult;
		this.picture = picture;
		this.firstDimensionDetails = firstDimensionDetails;
		this.secondDimensionDetails = secondDimensionDetails;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.Gel2dIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "separationResult"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.Gel2dIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public SeparationResult getSeparationResult() {
		return this.separationResult;
	}

	public void setSeparationResult(SeparationResult separationResult) {
		this.separationResult = separationResult;
	}

	@Column(name = "picture")
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Column(name = "first_dimension_details")
	public String getFirstDimensionDetails() {
		return this.firstDimensionDetails;
	}

	public void setFirstDimensionDetails(String firstDimensionDetails) {
		this.firstDimensionDetails = firstDimensionDetails;
	}

	@Column(name = "second_dimension_details")
	public String getSecondDimensionDetails() {
		return this.secondDimensionDetails;
	}

	public void setSecondDimensionDetails(String secondDimensionDetails) {
		this.secondDimensionDetails = secondDimensionDetails;
	}

}
