package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Gel2dMigrationProtocolApplication generated by hbm2java
 */
@Entity
@Table(name = "gel_2d_migration_protocol_application", schema = "public")
public class Gel2dMigrationProtocolApplication implements java.io.Serializable {

	private Gel2dMigrationProtocolApplicationId id;

	public Gel2dMigrationProtocolApplication() {
	}

	public Gel2dMigrationProtocolApplication(Gel2dMigrationProtocolApplicationId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "name", column = @Column(name = "name", length = 50)),
			@AttributeOverride(name = "date", column = @Column(name = "date")),
			@AttributeOverride(name = "actor", column = @Column(name = "actor")),
			@AttributeOverride(name = "comment", column = @Column(name = "comment")),
			@AttributeOverride(name = "protocol", column = @Column(name = "protocol")),
			@AttributeOverride(name = "result", column = @Column(name = "result")),
			@AttributeOverride(name = "massStart", column = @Column(name = "mass_start")),
			@AttributeOverride(name = "massEnd", column = @Column(name = "mass_end")),
			@AttributeOverride(name = "denaturingAgent", column = @Column(name = "denaturing_agent")),
			@AttributeOverride(name = "piStart", column = @Column(name = "pi_start")),
			@AttributeOverride(name = "piEnd", column = @Column(name = "pi_end")) })
	public Gel2dMigrationProtocolApplicationId getId() {
		return this.id;
	}

	public void setId(Gel2dMigrationProtocolApplicationId id) {
		this.id = id;
	}

}
