package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Gel2dResult generated by hbm2java
 */
@Entity
@Table(name = "gel_2d_result", schema = "public")
public class Gel2dResult implements java.io.Serializable {

	private Gel2dResultId id;

	public Gel2dResult() {
	}

	public Gel2dResult(Gel2dResultId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "name", column = @Column(name = "name")),
			@AttributeOverride(name = "picture", column = @Column(name = "picture")),
			@AttributeOverride(name = "firstDimensionDetails", column = @Column(name = "first_dimension_details")),
			@AttributeOverride(name = "secondDimensionDetails", column = @Column(name = "second_dimension_details")) })
	public Gel2dResultId getId() {
		return this.id;
	}

	public void setId(Gel2dResultId id) {
		this.id = id;
	}

}
