package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Gel2dMigration generated by hbm2java
 */
@Entity
@Table(name = "gel_2d_migration", schema = "public")
public class Gel2dMigration implements java.io.Serializable {

	private int id;
	private GelMigration gelMigration;
	private String piStart;
	private String piEnd;

	public Gel2dMigration() {
	}

	public Gel2dMigration(GelMigration gelMigration) {
		this.gelMigration = gelMigration;
	}

	public Gel2dMigration(GelMigration gelMigration, String piStart, String piEnd) {
		this.gelMigration = gelMigration;
		this.piStart = piStart;
		this.piEnd = piEnd;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.Gel2dMigrationIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "gelMigration"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.Gel2dMigrationIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public GelMigration getGelMigration() {
		return this.gelMigration;
	}

	public void setGelMigration(GelMigration gelMigration) {
		this.gelMigration = gelMigration;
	}

	@Column(name = "pi_start")
	public String getPiStart() {
		return this.piStart;
	}

	public void setPiStart(String piStart) {
		this.piStart = piStart;
	}

	@Column(name = "pi_end")
	public String getPiEnd() {
		return this.piEnd;
	}

	public void setPiEnd(String piEnd) {
		this.piEnd = piEnd;
	}

}
