package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Gel2dResultId generated by hbm2java
 */
@Embeddable
public class Gel2dResultId implements java.io.Serializable {

	private Integer id;
	private String name;
	private String picture;
	private String firstDimensionDetails;
	private String secondDimensionDetails;

	public Gel2dResultId() {
	}

	public Gel2dResultId(Integer id, String name, String picture, String firstDimensionDetails,
			String secondDimensionDetails) {
		this.id = id;
		this.name = name;
		this.picture = picture;
		this.firstDimensionDetails = firstDimensionDetails;
		this.secondDimensionDetails = secondDimensionDetails;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "picture")
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Column(name = "first_dimension_details")
	public String getFirstDimensionDetails() {
		return this.firstDimensionDetails;
	}

	public void setFirstDimensionDetails(String firstDimensionDetails) {
		this.firstDimensionDetails = firstDimensionDetails;
	}

	@Column(name = "second_dimension_details")
	public String getSecondDimensionDetails() {
		return this.secondDimensionDetails;
	}

	public void setSecondDimensionDetails(String secondDimensionDetails) {
		this.secondDimensionDetails = secondDimensionDetails;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Gel2dResultId))
			return false;
		Gel2dResultId castOther = (Gel2dResultId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getPicture() == castOther.getPicture()) || (this.getPicture() != null
						&& castOther.getPicture() != null && this.getPicture().equals(castOther.getPicture())))
				&& ((this.getFirstDimensionDetails() == castOther.getFirstDimensionDetails())
						|| (this.getFirstDimensionDetails() != null && castOther.getFirstDimensionDetails() != null
								&& this.getFirstDimensionDetails().equals(castOther.getFirstDimensionDetails())))
				&& ((this.getSecondDimensionDetails() == castOther.getSecondDimensionDetails())
						|| (this.getSecondDimensionDetails() != null && castOther.getSecondDimensionDetails() != null
								&& this.getSecondDimensionDetails().equals(castOther.getSecondDimensionDetails())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getPicture() == null ? 0 : this.getPicture().hashCode());
		result = 37 * result + (getFirstDimensionDetails() == null ? 0 : this.getFirstDimensionDetails().hashCode());
		result = 37 * result + (getSecondDimensionDetails() == null ? 0 : this.getSecondDimensionDetails().hashCode());
		return result;
	}

}
