package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GradientFractionLocatorId generated by hbm2java
 */
@Embeddable
public class GradientFractionLocatorId implements java.io.Serializable {

	private Integer id;
	private String sample;
	private Integer separationResult;
	private Integer number;

	public GradientFractionLocatorId() {
	}

	public GradientFractionLocatorId(Integer id, String sample, Integer separationResult, Integer number) {
		this.id = id;
		this.sample = sample;
		this.separationResult = separationResult;
		this.number = number;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sample")
	public String getSample() {
		return this.sample;
	}

	public void setSample(String sample) {
		this.sample = sample;
	}

	@Column(name = "separation_result")
	public Integer getSeparationResult() {
		return this.separationResult;
	}

	public void setSeparationResult(Integer separationResult) {
		this.separationResult = separationResult;
	}

	@Column(name = "number")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GradientFractionLocatorId))
			return false;
		GradientFractionLocatorId castOther = (GradientFractionLocatorId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getSample() == castOther.getSample()) || (this.getSample() != null
						&& castOther.getSample() != null && this.getSample().equals(castOther.getSample())))
				&& ((this.getSeparationResult() == castOther.getSeparationResult())
						|| (this.getSeparationResult() != null && castOther.getSeparationResult() != null
								&& this.getSeparationResult().equals(castOther.getSeparationResult())))
				&& ((this.getNumber() == castOther.getNumber()) || (this.getNumber() != null
						&& castOther.getNumber() != null && this.getNumber().equals(castOther.getNumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getSample() == null ? 0 : this.getSample().hashCode());
		result = 37 * result + (getSeparationResult() == null ? 0 : this.getSeparationResult().hashCode());
		result = 37 * result + (getNumber() == null ? 0 : this.getNumber().hashCode());
		return result;
	}

}
