package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * GradientFractionLocator generated by hbm2java
 */
@Entity
@Table(name = "gradient_fraction_locator", schema = "public")
public class GradientFractionLocator implements java.io.Serializable {

	private GradientFractionLocatorId id;

	public GradientFractionLocator() {
	}

	public GradientFractionLocator(GradientFractionLocatorId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "sample", column = @Column(name = "sample")),
			@AttributeOverride(name = "separationResult", column = @Column(name = "separation_result")),
			@AttributeOverride(name = "number", column = @Column(name = "number")) })
	public GradientFractionLocatorId getId() {
		return this.id;
	}

	public void setId(GradientFractionLocatorId id) {
		this.id = id;
	}

}
