package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.*;

/**
 * Instrument generated by hbm2java
 */
@Entity
@Table(name = "instrument", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Instrument implements java.io.Serializable {

	private int id;
	private String name;
	private String manufacturer;
	private String model;
	private String status;
	private Spectrometer spectrometer;
	private Robot robot;

	public Instrument() {
	}

	public Instrument(int id, String name, String model, String status) {
		this.id = id;
		this.name = name;
		this.model = model;
		this.status = status;
	}

	public Instrument(int id, String name, String manufacturer, String model, String status,
			Spectrometer spectrometer, Robot robot) {
		this.id = id;
		this.name = name;
		this.manufacturer = manufacturer;
		this.model = model;
		this.status = status;
		this.spectrometer = spectrometer;
		this.robot = robot;
	}

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE, generator = "instrument_generator")
	@SequenceGenerator(name = "instrument_generator", sequenceName = "instrument_id_seq", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "manufacturer")
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "model", nullable = false)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "status", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "instrument")
	public Spectrometer getSpectrometer() {
		return this.spectrometer;
	}

	public void setSpectrometer(Spectrometer spectrometer) {
		this.spectrometer = spectrometer;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "instrument")
	public Robot getRobot() {
		return this.robot;
	}

	public void setRobot(Robot robot) {
		this.robot = robot;
	}

}
