package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * LaneResult generated by hbm2java
 */
@Entity
@Table(name = "lane_result", schema = "public")
public class LaneResult implements java.io.Serializable {

	private LaneResultId id;

	public LaneResult() {
	}

	public LaneResult(LaneResultId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "name", column = @Column(name = "name")),
			@AttributeOverride(name = "picture", column = @Column(name = "picture")) })
	public LaneResultId getId() {
		return this.id;
	}

	public void setId(LaneResultId id) {
		this.id = id;
	}

}
