package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LaneResultId generated by hbm2java
 */
@Embeddable
public class LaneResultId implements java.io.Serializable {

	private Integer id;
	private String name;
	private String picture;

	public LaneResultId() {
	}

	public LaneResultId(Integer id, String name, String picture) {
		this.id = id;
		this.name = name;
		this.picture = picture;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "picture")
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LaneResultId))
			return false;
		LaneResultId castOther = (LaneResultId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getPicture() == castOther.getPicture()) || (this.getPicture() != null
						&& castOther.getPicture() != null && this.getPicture().equals(castOther.getPicture())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getPicture() == null ? 0 : this.getPicture().hashCode());
		return result;
	}

}
