package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LcFractionLocator generated by hbm2java
 */
@Entity
@Table(name = "lc_fraction_locator", schema = "public")
public class LcFractionLocator implements java.io.Serializable {

	private LcFractionLocatorId id;

	public LcFractionLocator() {
	}

	public LcFractionLocator(LcFractionLocatorId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "sample", column = @Column(name = "sample")),
			@AttributeOverride(name = "separationResult", column = @Column(name = "separation_result")),
			@AttributeOverride(name = "exitColumnTime", column = @Column(name = "exit_column_time")) })
	public LcFractionLocatorId getId() {
		return this.id;
	}

	public void setId(LcFractionLocatorId id) {
		this.id = id;
	}

}
