package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LcFractionLocatorId generated by hbm2java
 */
@Embeddable
public class LcFractionLocatorId implements java.io.Serializable {

	private Integer id;
	private String sample;
	private Integer separationResult;
	private String exitColumnTime;

	public LcFractionLocatorId() {
	}

	public LcFractionLocatorId(Integer id, String sample, Integer separationResult, String exitColumnTime) {
		this.id = id;
		this.sample = sample;
		this.separationResult = separationResult;
		this.exitColumnTime = exitColumnTime;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sample")
	public String getSample() {
		return this.sample;
	}

	public void setSample(String sample) {
		this.sample = sample;
	}

	@Column(name = "separation_result")
	public Integer getSeparationResult() {
		return this.separationResult;
	}

	public void setSeparationResult(Integer separationResult) {
		this.separationResult = separationResult;
	}

	@Column(name = "exit_column_time")
	public String getExitColumnTime() {
		return this.exitColumnTime;
	}

	public void setExitColumnTime(String exitColumnTime) {
		this.exitColumnTime = exitColumnTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LcFractionLocatorId))
			return false;
		LcFractionLocatorId castOther = (LcFractionLocatorId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getSample() == castOther.getSample()) || (this.getSample() != null
						&& castOther.getSample() != null && this.getSample().equals(castOther.getSample())))
				&& ((this.getSeparationResult() == castOther.getSeparationResult())
						|| (this.getSeparationResult() != null && castOther.getSeparationResult() != null
								&& this.getSeparationResult().equals(castOther.getSeparationResult())))
				&& ((this.getExitColumnTime() == castOther.getExitColumnTime())
						|| (this.getExitColumnTime() != null && castOther.getExitColumnTime() != null
								&& this.getExitColumnTime().equals(castOther.getExitColumnTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getSample() == null ? 0 : this.getSample().hashCode());
		result = 37 * result + (getSeparationResult() == null ? 0 : this.getSeparationResult().hashCode());
		result = 37 * result + (getExitColumnTime() == null ? 0 : this.getExitColumnTime().hashCode());
		return result;
	}

}
