package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * LcFraction generated by hbm2java
 */
@Entity
@Table(name = "lc_fraction", schema = "public")
public class LcFraction implements java.io.Serializable {

	private int id;
	private SampleLocator sampleLocator;
	private String exitColumnTime;

	public LcFraction() {
	}

	public LcFraction(SampleLocator sampleLocator) {
		this.sampleLocator = sampleLocator;
	}

	public LcFraction(SampleLocator sampleLocator, String exitColumnTime) {
		this.sampleLocator = sampleLocator;
		this.exitColumnTime = exitColumnTime;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.LcFractionIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "sampleLocator"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.LcFractionIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public SampleLocator getSampleLocator() {
		return this.sampleLocator;
	}

	public void setSampleLocator(SampleLocator sampleLocator) {
		this.sampleLocator = sampleLocator;
	}

	@Column(name = "exit_column_time")
	public String getExitColumnTime() {
		return this.exitColumnTime;
	}

	public void setExitColumnTime(String exitColumnTime) {
		this.exitColumnTime = exitColumnTime;
	}

}
