package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LiquidChromatographyProtocolApplication generated by hbm2java
 */
@Entity
@Table(name = "liquid_chromatography_protocol_application", schema = "public")
public class LiquidChromatographyProtocolApplication implements java.io.Serializable {

	private LiquidChromatographyProtocolApplicationId id;

	public LiquidChromatographyProtocolApplication() {
	}

	public LiquidChromatographyProtocolApplication(LiquidChromatographyProtocolApplicationId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "name", column = @Column(name = "name", length = 50)),
			@AttributeOverride(name = "date", column = @Column(name = "date")),
			@AttributeOverride(name = "actor", column = @Column(name = "actor")),
			@AttributeOverride(name = "comment", column = @Column(name = "comment")),
			@AttributeOverride(name = "protocol", column = @Column(name = "protocol")),
			@AttributeOverride(name = "result", column = @Column(name = "result")),
			@AttributeOverride(name = "stationaryPhase", column = @Column(name = "stationary_phase")),
			@AttributeOverride(name = "temperature", column = @Column(name = "temperature")),
			@AttributeOverride(name = "flowRate", column = @Column(name = "flow_rate")),
			@AttributeOverride(name = "injectionVolume", column = @Column(name = "injection_volume")),
			@AttributeOverride(name = "chromatographyColumn", column = @Column(name = "chromatography_column")) })
	public LiquidChromatographyProtocolApplicationId getId() {
		return this.id;
	}

	public void setId(LiquidChromatographyProtocolApplicationId id) {
		this.id = id;
	}

}
