package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LiquidChromatographyProtocolApplicationId generated by hbm2java
 */
@Embeddable
public class LiquidChromatographyProtocolApplicationId implements java.io.Serializable {

	private Integer id;
	private String name;
	private String date;
	private String actor;
	private String comment;
	private Integer protocol;
	private Integer result;
	private String stationaryPhase;
	private String temperature;
	private String flowRate;
	private String injectionVolume;
	private Integer chromatographyColumn;

	public LiquidChromatographyProtocolApplicationId() {
	}

	public LiquidChromatographyProtocolApplicationId(Integer id, String name, String date, String actor,
			String comment, Integer protocol, Integer result, String stationaryPhase,
			String temperature, String flowRate, String injectionVolume,
			Integer chromatographyColumn) {
		this.id = id;
		this.name = name;
		this.date = date;
		this.actor = actor;
		this.comment = comment;
		this.protocol = protocol;
		this.result = result;
		this.stationaryPhase = stationaryPhase;
		this.temperature = temperature;
		this.flowRate = flowRate;
		this.injectionVolume = injectionVolume;
		this.chromatographyColumn = chromatographyColumn;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "date")
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "actor")
	public String getActor() {
		return this.actor;
	}

	public void setActor(String actor) {
		this.actor = actor;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "protocol")
	public Integer getProtocol() {
		return this.protocol;
	}

	public void setProtocol(Integer protocol) {
		this.protocol = protocol;
	}

	@Column(name = "result")
	public Integer getResult() {
		return this.result;
	}

	public void setResult(Integer result) {
		this.result = result;
	}

	@Column(name = "stationary_phase")
	public String getStationaryPhase() {
		return this.stationaryPhase;
	}

	public void setStationaryPhase(String stationaryPhase) {
		this.stationaryPhase = stationaryPhase;
	}

	@Column(name = "temperature")
	public String getTemperature() {
		return this.temperature;
	}

	public void setTemperature(String temperature) {
		this.temperature = temperature;
	}

	@Column(name = "flow_rate")
	public String getFlowRate() {
		return this.flowRate;
	}

	public void setFlowRate(String flowRate) {
		this.flowRate = flowRate;
	}

	@Column(name = "injection_volume")
	public String getInjectionVolume() {
		return this.injectionVolume;
	}

	public void setInjectionVolume(String injectionVolume) {
		this.injectionVolume = injectionVolume;
	}

	@Column(name = "chromatography_column")
	public Integer getChromatographyColumn() {
		return this.chromatographyColumn;
	}

	public void setChromatographyColumn(Integer chromatographyColumn) {
		this.chromatographyColumn = chromatographyColumn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LiquidChromatographyProtocolApplicationId))
			return false;
		LiquidChromatographyProtocolApplicationId castOther = (LiquidChromatographyProtocolApplicationId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())))
				&& ((this.getActor() == castOther.getActor()) || (this.getActor() != null
						&& castOther.getActor() != null && this.getActor().equals(castOther.getActor())))
				&& ((this.getComment() == castOther.getComment()) || (this.getComment() != null
						&& castOther.getComment() != null && this.getComment().equals(castOther.getComment())))
				&& ((this.getProtocol() == castOther.getProtocol()) || (this.getProtocol() != null
						&& castOther.getProtocol() != null && this.getProtocol().equals(castOther.getProtocol())))
				&& ((this.getResult() == castOther.getResult()) || (this.getResult() != null
						&& castOther.getResult() != null && this.getResult().equals(castOther.getResult())))
				&& ((this.getStationaryPhase() == castOther.getStationaryPhase())
						|| (this.getStationaryPhase() != null && castOther.getStationaryPhase() != null
								&& this.getStationaryPhase().equals(castOther.getStationaryPhase())))
				&& ((this.getTemperature() == castOther.getTemperature())
						|| (this.getTemperature() != null && castOther.getTemperature() != null
								&& this.getTemperature().equals(castOther.getTemperature())))
				&& ((this.getFlowRate() == castOther.getFlowRate()) || (this.getFlowRate() != null
						&& castOther.getFlowRate() != null && this.getFlowRate().equals(castOther.getFlowRate())))
				&& ((this.getInjectionVolume() == castOther.getInjectionVolume())
						|| (this.getInjectionVolume() != null && castOther.getInjectionVolume() != null
								&& this.getInjectionVolume().equals(castOther.getInjectionVolume())))
				&& ((this.getChromatographyColumn() == castOther.getChromatographyColumn())
						|| (this.getChromatographyColumn() != null && castOther.getChromatographyColumn() != null
								&& this.getChromatographyColumn().equals(castOther.getChromatographyColumn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getActor() == null ? 0 : this.getActor().hashCode());
		result = 37 * result + (getComment() == null ? 0 : this.getComment().hashCode());
		result = 37 * result + (getProtocol() == null ? 0 : this.getProtocol().hashCode());
		result = 37 * result + (getResult() == null ? 0 : this.getResult().hashCode());
		result = 37 * result + (getStationaryPhase() == null ? 0 : this.getStationaryPhase().hashCode());
		result = 37 * result + (getTemperature() == null ? 0 : this.getTemperature().hashCode());
		result = 37 * result + (getFlowRate() == null ? 0 : this.getFlowRate().hashCode());
		result = 37 * result + (getInjectionVolume() == null ? 0 : this.getInjectionVolume().hashCode());
		result = 37 * result + (getChromatographyColumn() == null ? 0 : this.getChromatographyColumn().hashCode());
		return result;
	}

}
