package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MsmsAcquisitionProtocol generated by hbm2java
 */
@Entity
@Table(name = "msms_acquisition_protocol", schema = "public")
public class MsmsAcquisitionProtocol implements java.io.Serializable {

	private MsmsAcquisitionProtocolId id;

	public MsmsAcquisitionProtocol() {
	}

	public MsmsAcquisitionProtocol(MsmsAcquisitionProtocolId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "title", column = @Column(name = "title")),
			@AttributeOverride(name = "reference", column = @Column(name = "reference")),
			@AttributeOverride(name = "version", column = @Column(name = "version")),
			@AttributeOverride(name = "creationDate", column = @Column(name = "creation_date")),
			@AttributeOverride(name = "softwareVersion", column = @Column(name = "software_version")),
			@AttributeOverride(name = "softwareName", column = @Column(name = "software_name")),
			@AttributeOverride(name = "parametersFile", column = @Column(name = "parameters_file")),
			@AttributeOverride(name = "selectedMass", column = @Column(name = "selected_mass")),
			@AttributeOverride(name = "runTime", column = @Column(name = "run_time")) })
	public MsmsAcquisitionProtocolId getId() {
		return this.id;
	}

	public void setId(MsmsAcquisitionProtocolId id) {
		this.id = id;
	}

}
