package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Plate generated by hbm2java
 */
@Entity
@Table(name = "plate", schema = "public")
public class Plate implements java.io.Serializable {

	private String name;
	private int XSize;
	private int YSize;
	private Set<Well> wells = new HashSet<Well>(0);
	private Set<RunRobot> runRobots = new HashSet<RunRobot>(0);

	public Plate() {
	}

	public Plate(String name, int XSize, int YSize) {
		this.name = name;
		this.XSize = XSize;
		this.YSize = YSize;
	}

	public Plate(String name, int XSize, int YSize, Set<Well> wells, Set<RunRobot> runRobots) {
		this.name = name;
		this.XSize = XSize;
		this.YSize = YSize;
		this.wells = wells;
		this.runRobots = runRobots;
	}

	@Id

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "x_size", nullable = false)
	public int getXSize() {
		return this.XSize;
	}

	public void setXSize(int XSize) {
		this.XSize = XSize;
	}

	@Column(name = "y_size", nullable = false)
	public int getYSize() {
		return this.YSize;
	}

	public void setYSize(int YSize) {
		this.YSize = YSize;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plate")
	public Set<Well> getWells() {
		return this.wells;
	}

	public void setWells(Set<Well> wells) {
		this.wells = wells;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plate")
	public Set<RunRobot> getRunRobots() {
		return this.runRobots;
	}

	public void setRunRobots(Set<RunRobot> runRobots) {
		this.runRobots = runRobots;
	}

}
