package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * PoolProtocolApplication generated by hbm2java
 */
@Entity
@Table(name = "pool_protocol_application", schema = "public")
public class PoolProtocolApplication implements java.io.Serializable {

	private PoolProtocolApplicationId id;

	public PoolProtocolApplication() {
	}

	public PoolProtocolApplication(PoolProtocolApplicationId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "name", column = @Column(name = "name", length = 50)),
			@AttributeOverride(name = "date", column = @Column(name = "date")),
			@AttributeOverride(name = "actor", column = @Column(name = "actor")),
			@AttributeOverride(name = "comment", column = @Column(name = "comment")),
			@AttributeOverride(name = "protocol", column = @Column(name = "protocol")),
			@AttributeOverride(name = "resultSample", column = @Column(name = "result_sample")) })
	public PoolProtocolApplicationId getId() {
		return this.id;
	}

	public void setId(PoolProtocolApplicationId id) {
		this.id = id;
	}

}
