package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Pool generated by hbm2java
 */
@Entity
@Table(name = "pool", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "result_sample"))
public class Pool implements java.io.Serializable {

	private int id;
	private ProtocolApplication protocolApplication;
	private Sample sample;

	public Pool() {
	}

	public Pool(ProtocolApplication protocolApplication) {
		this.protocolApplication = protocolApplication;
	}

	public Pool(ProtocolApplication protocolApplication, Sample sample) {
		this.protocolApplication = protocolApplication;
		this.sample = sample;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.PoolIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "protocolApplication"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.PoolIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public ProtocolApplication getProtocolApplication() {
		return this.protocolApplication;
	}

	public void setProtocolApplication(ProtocolApplication protocolApplication) {
		this.protocolApplication = protocolApplication;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "result_sample", unique = true)
	public Sample getSample() {
		return this.sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

}
