package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Program generated by hbm2java
 */
@Entity
@Table(name = "program", schema = "public", uniqueConstraints = { @UniqueConstraint(columnNames = "nomenclature_title"),
		@UniqueConstraint(columnNames = "title") })
public class Program implements java.io.Serializable {

	private int id;
	private String title;
	private String nomenclatureTitle;
	private String longTitle;
	private String description;
	private String contractualFrame;
	private String responsible;
	private Date closingDate;
	private Date creationDate;
	private Boolean confidential;
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<Actor> actors = new HashSet<Actor>(0);
	private Set<ProgContacts> progContactses = new HashSet<ProgContacts>(0);

	public Program() {
	}

	public Program(int id, String title, String nomenclatureTitle, String responsible,
			Date creationDate) {
		this.id = id;
		this.title = title;
		this.nomenclatureTitle = nomenclatureTitle;
		this.responsible = responsible;
		this.creationDate = creationDate;
	}

	public Program(int id, String title, String nomenclatureTitle, String longTitle,
			String description, String contractualFrame, String responsible, Date closingDate,
			Date creationDate, Boolean confidential, Set<Project> projects, Set<Actor> actors,
			Set<ProgContacts> progContactses) {
		this.id = id;
		this.title = title;
		this.nomenclatureTitle = nomenclatureTitle;
		this.longTitle = longTitle;
		this.description = description;
		this.contractualFrame = contractualFrame;
		this.responsible = responsible;
		this.closingDate = closingDate;
		this.creationDate = creationDate;
		this.confidential = confidential;
		this.projects = projects;
		this.actors = actors;
		this.progContactses = progContactses;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "program_generator")
	@SequenceGenerator(name = "program_generator", sequenceName = "program_id_seq", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", unique = true, nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "nomenclature_title", unique = true, nullable = false, length = 10)
	public String getNomenclatureTitle() {
		return this.nomenclatureTitle;
	}

	public void setNomenclatureTitle(String nomenclatureTitle) {
		this.nomenclatureTitle = nomenclatureTitle;
	}

	@Column(name = "long_title")
	public String getLongTitle() {
		return this.longTitle;
	}

	public void setLongTitle(String longTitle) {
		this.longTitle = longTitle;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "contractual_frame")
	public String getContractualFrame() {
		return this.contractualFrame;
	}

	public void setContractualFrame(String contractualFrame) {
		this.contractualFrame = contractualFrame;
	}

	@Column(name = "responsible", nullable = false)
	public String getResponsible() {
		return this.responsible;
	}

	public void setResponsible(String responsible) {
		this.responsible = responsible;
	}

	@Column(name = "closing_date")
	public Date getClosingDate() {
		return this.closingDate;
	}

	public void setClosingDate(Date closingDate) {
		this.closingDate = closingDate;
	}

	@Column(name = "creation_date", nullable = false)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "confidential")
	public Boolean getConfidential() {
		return this.confidential;
	}

	public void setConfidential(Boolean confidential) {
		this.confidential = confidential;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "program")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "progs_actors", schema = "public", joinColumns = {
			@JoinColumn(name = "program_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "actor_id", nullable = false, updatable = false) })
	public Set<Actor> getActors() {
		return this.actors;
	}

	public void setActors(Set<Actor> actors) {
		this.actors = actors;
	}

	public void addActor(Actor a) {
		this.actors.add(a);
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "program")
	public Set<ProgContacts> getProgContactses() {
		return this.progContactses;
	}

	public void setProgContactses(Set<ProgContacts> progContactses) {
		this.progContactses = progContactses;
	}

}
