package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.*;

/**
 * ProjContacts generated by hbm2java
 */
@Entity
@Table(name = "proj_contacts", schema = "public")
public class ProjContacts implements java.io.Serializable {

	private int id;
	private Contact contact;
	private Project project;

	public ProjContacts() {
	}

	public ProjContacts(Contact contact, Project project) {
		this.contact = contact;
		this.project = project;
	}

	public ProjContacts(int id, Contact contact, Project project) {
		this.id = id;
		this.contact = contact;
		this.project = project;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "proj_contacts_generator")
	@SequenceGenerator(name = "proj_contacts_generator", sequenceName = "proj_contacts_id_seq", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact", nullable = false)
	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

}
