package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", schema = "public", uniqueConstraints = { @UniqueConstraint(columnNames = "nomenclature_title"),
		@UniqueConstraint(columnNames = "title") })
public class Project implements java.io.Serializable {

	private int id;
	private Actor actor;
	private Program program;
	private String title;
	private String nomenclatureTitle;
	private String longTitle;
	private String description;
	private String contractualFrame;
	private String identificationType;

	@Temporal(TemporalType.DATE)
	private Date creationDate;

	@Temporal(TemporalType.DATE)
	private Date closingDate;

	private Boolean confidential;
	private Set<ProjContacts> projContactses = new HashSet<ProjContacts>(0);
	private Set<Study> studies = new HashSet<Study>(0);
	private Set<Actor> actors = new HashSet<Actor>(0);

	public Project() {
	}

	public Project(int id, Actor actor, String title, String nomenclatureTitle, Date creationDate) {
		this.id = id;
		this.actor = actor;
		this.title = title;
		this.nomenclatureTitle = nomenclatureTitle;
		this.creationDate = creationDate;
	}

	public Project(Actor actor, Program program, String title, String nomenclatureTitle,
				   String longTitle, String description, String contractualFrame,
				   String identificationType, Date creationDate, Date closingDate, Boolean confidential,
				   Set<ProjContacts> projContactses, Set<Study> studies, Set<Actor> actors) {
		this.actor = actor;
		this.program = program;
		this.title = title;
		this.nomenclatureTitle = nomenclatureTitle;
		this.longTitle = longTitle;
		this.description = description;
		this.contractualFrame = contractualFrame;
		this.identificationType = identificationType;
		this.creationDate = creationDate;
		this.closingDate = closingDate;
		this.confidential = confidential;
		this.projContactses = projContactses;
		this.studies = studies;
		this.actors = actors;
	}

	public Project(int id, Actor actor, Program program, String title, String nomenclatureTitle,
			String longTitle, String description, String contractualFrame,
			String identificationType, Date creationDate, Date closingDate, Boolean confidential,
			Set<ProjContacts> projContactses, Set<Study> studies, Set<Actor> actors) {
		this.id = id;
		this.actor = actor;
		this.program = program;
		this.title = title;
		this.nomenclatureTitle = nomenclatureTitle;
		this.longTitle = longTitle;
		this.description = description;
		this.contractualFrame = contractualFrame;
		this.identificationType = identificationType;
		this.creationDate = creationDate;
		this.closingDate = closingDate;
		this.confidential = confidential;
		this.projContactses = projContactses;
		this.studies = studies;
		this.actors = actors;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "project_generator")
	@SequenceGenerator(name = "project_generator", sequenceName = "project_id_seq", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "responsible", nullable = false)
	public Actor getActor() {
		return this.actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "program")
	public Program getProgram() {
		return this.program;
	}

	public void setProgram(Program program) {
		this.program = program;
	}

	@Column(name = "title", unique = true, nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "nomenclature_title", unique = true, nullable = false, length = 10)
	public String getNomenclatureTitle() {
		return this.nomenclatureTitle;
	}

	public void setNomenclatureTitle(String nomenclatureTitle) {
		this.nomenclatureTitle = nomenclatureTitle;
	}

	@Column(name = "long_title")
	public String getLongTitle() {
		return this.longTitle;
	}

	public void setLongTitle(String longTitle) {
		this.longTitle = longTitle;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "contractual_frame")
	public String getContractualFrame() {
		return this.contractualFrame;
	}

	public void setContractualFrame(String contractualFrame) {
		this.contractualFrame = contractualFrame;
	}

	@Column(name = "identification_type")
	public String getIdentificationType() {
		return this.identificationType;
	}

	public void setIdentificationType(String identificationType) {
		this.identificationType = identificationType;
	}

	@Column(name = "creation_date", nullable = false)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "closing_date")
	public Date getClosingDate() {
		return this.closingDate;
	}

	public void setClosingDate(Date closingDate) {
		this.closingDate = closingDate;
	}

	@Column(name = "confidential")
	public Boolean getConfidential() {
		return this.confidential;
	}

	public void setConfidential(Boolean confidential) {
		this.confidential = confidential;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<ProjContacts> getProjContactses() {
		return this.projContactses;
	}

	public void setProjContactses(Set<ProjContacts> projContactses) {
		this.projContactses = projContactses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<Study> getStudies() {
		return this.studies;
	}

	public void setStudies(Set<Study> studies) {
		this.studies = studies;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "projs_actors", schema = "public", joinColumns = {
			@JoinColumn(name = "proj_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "actor_id", nullable = false, updatable = false) })
	public Set<Actor> getActors() {
		return this.actors;
	}

	public void setActors(Set<Actor> actors) {
		this.actors = actors;
	}

	public void addActor(Actor a) {
		this.actors.add(a);
	}

}
