package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProtocolStep generated by hbm2java
 */
@Entity
@Table(name = "protocol_step", schema = "public")
public class ProtocolStep implements java.io.Serializable {

	private int id;
	private Protocol protocolByStep;
	private Protocol protocolByDescribedProtocol;
	private int rank;

	public ProtocolStep() {
	}

	public ProtocolStep(int id, Protocol protocolByStep, Protocol protocolByDescribedProtocol, int rank) {
		this.id = id;
		this.protocolByStep = protocolByStep;
		this.protocolByDescribedProtocol = protocolByDescribedProtocol;
		this.rank = rank;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "step", nullable = false)
	public Protocol getProtocolByStep() {
		return this.protocolByStep;
	}

	public void setProtocolByStep(Protocol protocolByStep) {
		this.protocolByStep = protocolByStep;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "described_protocol", nullable = false)
	public Protocol getProtocolByDescribedProtocol() {
		return this.protocolByDescribedProtocol;
	}

	public void setProtocolByDescribedProtocol(Protocol protocolByDescribedProtocol) {
		this.protocolByDescribedProtocol = protocolByDescribedProtocol;
	}

	@Column(name = "rank", nullable = false)
	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

}
