package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Reference generated by hbm2java
 */
@Entity
@Table(name = "reference", schema = "public")
public class Reference implements java.io.Serializable {

	private int id;
	private Document document;
	private Set<Protocol> protocols = new HashSet<Protocol>(0);
	private TextDescription textDescription;

	public Reference() {
	}

	public Reference(int id) {
		this.id = id;
	}

	public Reference(int id, Document document, Set<Protocol> protocols, TextDescription textDescription) {
		this.id = id;
		this.document = document;
		this.protocols = protocols;
		this.textDescription = textDescription;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "reference")
	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reference")
	public Set<Protocol> getProtocols() {
		return this.protocols;
	}

	public void setProtocols(Set<Protocol> protocols) {
		this.protocols = protocols;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "reference")
	public TextDescription getTextDescription() {
		return this.textDescription;
	}

	public void setTextDescription(TextDescription textDescription) {
		this.textDescription = textDescription;
	}

}
