package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Robot generated by hbm2java
 */
@Entity
@Table(name = "robot", schema = "public")
public class Robot implements java.io.Serializable {

	private int id;
	private Instrument instrument;
	private Set<RunRobot> runRobots = new HashSet<RunRobot>(0);

	public Robot() {
	}

	public Robot(Instrument instrument) {
		this.instrument = instrument;
	}

	public Robot(Instrument instrument, Set<RunRobot> runRobots) {
		this.instrument = instrument;
		this.runRobots = runRobots;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.RobotIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "instrument"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.RobotIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Instrument getInstrument() {
		return this.instrument;
	}

	public void setInstrument(Instrument instrument) {
		this.instrument = instrument;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "robot")
	public Set<RunRobot> getRunRobots() {
		return this.runRobots;
	}

	public void setRunRobots(Set<RunRobot> runRobots) {
		this.runRobots = runRobots;
	}

}
