package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * RobotPlanning generated by hbm2java
 */
@Entity
@Table(name = "robot_planning", schema = "public")
public class RobotPlanning implements java.io.Serializable {

	private int id;
	private Actor actor;
	private Sample sample;
	private Float trypsineVol;
	private Float proteinQty;
	private String separationResultClass;
	private Date date;
	private int loadCount;
	private String description;
	private Boolean sampleConsumed;
	private String name;
	private Set<VirtualWell> virtualWells = new HashSet<>(0);

	public RobotPlanning() {
	}

	public RobotPlanning(int id, Sample sample, int loadCount) {
		this.id = id;
		this.sample = sample;
		this.loadCount = loadCount;
	}

	public RobotPlanning(Actor actor, Sample sample, Float trypsineVol, Float proteinQty,
			String separationResultClass, Date date, int loadCount, String description,
						 Boolean sampleConsumed, String name, Set<VirtualWell> virtualWells) {
		this.actor = actor;
		this.sample = sample;
		this.trypsineVol = trypsineVol;
		this.proteinQty = proteinQty;
		this.separationResultClass = separationResultClass;
		this.date = date;
		this.loadCount = loadCount;
		this.description = description;
		this.sampleConsumed = sampleConsumed;
		this.name = name;
		this.virtualWells = virtualWells;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "robot_planning_generator")
	@SequenceGenerator(name = "robot_planning_generator", sequenceName = "robot_planning_id_seq", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "actor")
	public Actor getActor() {
		return this.actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sample", nullable = false)
	public Sample getSample() {
		return this.sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

	@Column(name = "trypsine_vol")
	public Float getTrypsineVol() {
		return this.trypsineVol;
	}

	public void setTrypsineVol(Float trypsineVol) {
		this.trypsineVol = trypsineVol;
	}

	@Column(name = "protein_qty")
	public Float getProteinQty() {
		return this.proteinQty;
	}

	public void setProteinQty(Float proteinQty) {
		this.proteinQty = proteinQty;
	}

	@Column(name = "separation_result_class")
	public String getSeparationResultClass() {
		return this.separationResultClass;
	}

	public void setSeparationResultClass(String separationResultClass) {
		this.separationResultClass = separationResultClass;
	}

	@Column(name = "date")
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "load_count", nullable = false)
	public int getLoadCount() {
		return this.loadCount;
	}

	public void setLoadCount(int loadCount) {
		this.loadCount = loadCount;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "sample_consumed")
	public Boolean getSampleConsumed() {
		return this.sampleConsumed;
	}

	public void setSampleConsumed(Boolean sampleConsumed) {
		this.sampleConsumed = sampleConsumed;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "robotPlanning")
	public Set<VirtualWell> getVirtualWells() {
		return this.virtualWells;
	}

	public void setVirtualWells(Set<VirtualWell> virtualWells) {
		this.virtualWells = virtualWells;
	}

}
