package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * SampleType generated by hbm2java
 */
@Entity
@Table(name = "sample_type", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class SampleType implements java.io.Serializable {

	private int id;
	private String name;
	private Set<BiologicOrigin> biologicOrigins = new HashSet<BiologicOrigin>(0);

	public SampleType() {
	}

	public SampleType(String name, Set<BiologicOrigin> biologicOrigins) {
		this.name = name;
		this.biologicOrigins = null;
	}

	public SampleType(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public SampleType(int id, String name, Set<BiologicOrigin> biologicOrigins) {
		this.id = id;
		this.name = name;
		this.biologicOrigins = biologicOrigins;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "sample_type_generator")
	@SequenceGenerator(name = "sample_type_generator", sequenceName = "sample_species_id_seq", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sampleType")
	public Set<BiologicOrigin> getBiologicOrigins() {
		return this.biologicOrigins;
	}

	public void setBiologicOrigins(Set<BiologicOrigin> biologicOrigins) {
		this.biologicOrigins = biologicOrigins;
	}

}
