package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SamplesSetResultId generated by hbm2java
 */
@Embeddable
public class SamplesSetResultId implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer samplesCount;

	public SamplesSetResultId() {
	}

	public SamplesSetResultId(Integer id, String name, Integer samplesCount) {
		this.id = id;
		this.name = name;
		this.samplesCount = samplesCount;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "samples_count")
	public Integer getSamplesCount() {
		return this.samplesCount;
	}

	public void setSamplesCount(Integer samplesCount) {
		this.samplesCount = samplesCount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SamplesSetResultId))
			return false;
		SamplesSetResultId castOther = (SamplesSetResultId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getSamplesCount() == castOther.getSamplesCount())
						|| (this.getSamplesCount() != null && castOther.getSamplesCount() != null
								&& this.getSamplesCount().equals(castOther.getSamplesCount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getSamplesCount() == null ? 0 : this.getSamplesCount().hashCode());
		return result;
	}

}
