package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SampleKind generated by hbm2java
 */
@Entity
@Table(name = "sample_kind", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class SampleKind implements java.io.Serializable {

	private int id;
	private String name;
	private Set<BiologicOrigin> biologicOrigins = new HashSet<BiologicOrigin>(0);

	public SampleKind() {
	}

	public SampleKind(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public SampleKind(int id, String name, Set<BiologicOrigin> biologicOrigins) {
		this.id = id;
		this.name = name;
		this.biologicOrigins = biologicOrigins;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sampleKind")
	public Set<BiologicOrigin> getBiologicOrigins() {
		return this.biologicOrigins;
	}

	public void setBiologicOrigins(Set<BiologicOrigin> biologicOrigins) {
		this.biologicOrigins = biologicOrigins;
	}

}
