package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * SamplesSet generated by hbm2java
 */
@Entity
@Table(name = "samples_set", schema = "public")
public class SamplesSet implements java.io.Serializable {

	private int id;
	private SeparationResult separationResult;
	private Integer samplesCount;

	public SamplesSet() {
	}

	public SamplesSet(SeparationResult separationResult) {
		this.separationResult = separationResult;
	}

	public SamplesSet(SeparationResult separationResult, Integer samplesCount) {
		this.separationResult = separationResult;
		this.samplesCount = samplesCount;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.SamplesSetIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "separationResult"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.SamplesSetIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public SeparationResult getSeparationResult() {
		return this.separationResult;
	}

	public void setSeparationResult(SeparationResult separationResult) {
		this.separationResult = separationResult;
	}

	@Column(name = "samples_count")
	public Integer getSamplesCount() {
		return this.samplesCount;
	}

	public void setSamplesCount(Integer samplesCount) {
		this.samplesCount = samplesCount;
	}

}
