package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * SamplesSetResult generated by hbm2java
 */
@Entity
@Table(name = "samples_set_result", schema = "public")
public class SamplesSetResult implements java.io.Serializable {

	private SamplesSetResultId id;

	public SamplesSetResult() {
	}

	public SamplesSetResult(SamplesSetResultId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "name", column = @Column(name = "name")),
			@AttributeOverride(name = "samplesCount", column = @Column(name = "samples_count")) })
	public SamplesSetResultId getId() {
		return this.id;
	}

	public void setId(SamplesSetResultId id) {
		this.id = id;
	}

}
