package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * SeparationResult generated by hbm2java
 */
@Entity
@Table(name = "separation_result", schema = "public")
public class SeparationResult implements java.io.Serializable {

	private int id;
	private String name;
	private String comment;
	private Set<Separation> separations = new HashSet<Separation>(0);
	private Lane lane;
	private SamplesSet samplesSet;
	private Set<Study> studies = new HashSet<Study>(0);
	private Set<SampleLocator> sampleLocators = new HashSet<SampleLocator>(0);
	private Gel2d gel2d;

	public SeparationResult() {
	}

	public SeparationResult(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public SeparationResult(String name, String comment, Set<Separation> separations, Lane lane,
							SamplesSet samplesSet, Set<Study> studies, Set<SampleLocator> sampleLocators, Gel2d gel2d) {
		this.id = id;
		this.name = name;
		this.comment = comment;
		this.separations = separations;
		this.lane = lane;
		this.samplesSet = samplesSet;
		this.studies = studies;
		this.sampleLocators = sampleLocators;
		this.gel2d = gel2d;
	}

	public SeparationResult(int id, String name, String comment, Set<Separation> separations, Lane lane,
			SamplesSet samplesSet, Set<Study> studies, Set<SampleLocator> sampleLocators, Gel2d gel2d) {
		this.id = id;
		this.name = name;
		this.comment = comment;
		this.separations = separations;
		this.lane = lane;
		this.samplesSet = samplesSet;
		this.studies = studies;
		this.sampleLocators = sampleLocators;
		this.gel2d = gel2d;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "separation_result_generator")
	@SequenceGenerator(name = "separation_result_generator", sequenceName = "separation_result_id_seq", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, columnDefinition="TEXT")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "separationResult")
	public Set<Separation> getSeparations() {
		return this.separations;
	}

	public void setSeparations(Set<Separation> separations) {
		this.separations = separations;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "separationResult")
	public Lane getLane() {
		return this.lane;
	}

	public void setLane(Lane lane) {
		this.lane = lane;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "separationResult")
	public SamplesSet getSamplesSet() {
		return this.samplesSet;
	}

	public void setSamplesSet(SamplesSet samplesSet) {
		this.samplesSet = samplesSet;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "samples_share", schema = "public", joinColumns = {
			@JoinColumn(name = "separation_result", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "study", nullable = false, updatable = false) })
	public Set<Study> getStudies() {
		return this.studies;
	}

	public void setStudies(Set<Study> studies) {
		this.studies = studies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "separationResult")
	public Set<SampleLocator> getSampleLocators() {
		return this.sampleLocators;
	}

	public void setSampleLocators(Set<SampleLocator> sampleLocators) {
		this.sampleLocators = sampleLocators;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "separationResult")
	public Gel2d getGel2d() {
		return this.gel2d;
	}

	public void setGel2d(Gel2d gel2d) {
		this.gel2d = gel2d;
	}

}
