package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Spectrometer generated by hbm2java
 */
@Entity
@Table(name = "spectrometer", schema = "public")
public class Spectrometer implements java.io.Serializable {

	private int id;
	private Instrument instrument;
	private Set<Acquisition> acquisitions = new HashSet<Acquisition>(0);

	public Spectrometer() {
	}

	public Spectrometer(Instrument instrument) {
		this.instrument = instrument;
	}

	public Spectrometer(Instrument instrument, Set<Acquisition> acquisitions) {
		this.instrument = instrument;
		this.acquisitions = acquisitions;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.SpectrometerIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "instrument"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.SpectrometerIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Instrument getInstrument() {
		return this.instrument;
	}

	public void setInstrument(Instrument instrument) {
		this.instrument = instrument;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spectrometer")
	public Set<Acquisition> getAcquisitions() {
		return this.acquisitions;
	}

	public void setAcquisitions(Set<Acquisition> acquisitions) {
		this.acquisitions = acquisitions;
	}

}
