package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SpotLocatorId generated by hbm2java
 */
@Embeddable
public class SpotLocatorId implements java.io.Serializable {

	private Integer id;
	private String sample;
	private Integer separationResult;
	private String experimentalMass;
	private String experimentalIp;

	public SpotLocatorId() {
	}

	public SpotLocatorId(Integer id, String sample, Integer separationResult, String experimentalMass,
			String experimentalIp) {
		this.id = id;
		this.sample = sample;
		this.separationResult = separationResult;
		this.experimentalMass = experimentalMass;
		this.experimentalIp = experimentalIp;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sample")
	public String getSample() {
		return this.sample;
	}

	public void setSample(String sample) {
		this.sample = sample;
	}

	@Column(name = "separation_result")
	public Integer getSeparationResult() {
		return this.separationResult;
	}

	public void setSeparationResult(Integer separationResult) {
		this.separationResult = separationResult;
	}

	@Column(name = "experimental_mass")
	public String getExperimentalMass() {
		return this.experimentalMass;
	}

	public void setExperimentalMass(String experimentalMass) {
		this.experimentalMass = experimentalMass;
	}

	@Column(name = "experimental_ip")
	public String getExperimentalIp() {
		return this.experimentalIp;
	}

	public void setExperimentalIp(String experimentalIp) {
		this.experimentalIp = experimentalIp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpotLocatorId))
			return false;
		SpotLocatorId castOther = (SpotLocatorId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getSample() == castOther.getSample()) || (this.getSample() != null
						&& castOther.getSample() != null && this.getSample().equals(castOther.getSample())))
				&& ((this.getSeparationResult() == castOther.getSeparationResult())
						|| (this.getSeparationResult() != null && castOther.getSeparationResult() != null
								&& this.getSeparationResult().equals(castOther.getSeparationResult())))
				&& ((this.getExperimentalMass() == castOther.getExperimentalMass())
						|| (this.getExperimentalMass() != null && castOther.getExperimentalMass() != null
								&& this.getExperimentalMass().equals(castOther.getExperimentalMass())))
				&& ((this.getExperimentalIp() == castOther.getExperimentalIp())
						|| (this.getExperimentalIp() != null && castOther.getExperimentalIp() != null
								&& this.getExperimentalIp().equals(castOther.getExperimentalIp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getSample() == null ? 0 : this.getSample().hashCode());
		result = 37 * result + (getSeparationResult() == null ? 0 : this.getSeparationResult().hashCode());
		result = 37 * result + (getExperimentalMass() == null ? 0 : this.getExperimentalMass().hashCode());
		result = 37 * result + (getExperimentalIp() == null ? 0 : this.getExperimentalIp().hashCode());
		return result;
	}

}
