package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SpotLocator generated by hbm2java
 */
@Entity
@Table(name = "spot_locator", schema = "public")
public class SpotLocator implements java.io.Serializable {

	private SpotLocatorId id;

	public SpotLocator() {
	}

	public SpotLocator(SpotLocatorId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "sample", column = @Column(name = "sample")),
			@AttributeOverride(name = "separationResult", column = @Column(name = "separation_result")),
			@AttributeOverride(name = "experimentalMass", column = @Column(name = "experimental_mass")),
			@AttributeOverride(name = "experimentalIp", column = @Column(name = "experimental_ip")) })
	public SpotLocatorId getId() {
		return this.id;
	}

	public void setId(SpotLocatorId id) {
		this.id = id;
	}

}
