package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Spot generated by hbm2java
 */
@Entity
@Table(name = "spot", schema = "public")
public class Spot implements java.io.Serializable {

	private int id;
	private SampleLocator sampleLocator;
	private String experimentalMass;
	private String experimentalIp;

	public Spot() {
	}

	public Spot(SampleLocator sampleLocator) {
		this.sampleLocator = sampleLocator;
	}

	public Spot(SampleLocator sampleLocator, String experimentalMass, String experimentalIp) {
		this.sampleLocator = sampleLocator;
		this.experimentalMass = experimentalMass;
		this.experimentalIp = experimentalIp;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.SpotIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "sampleLocator"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.SpotIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public SampleLocator getSampleLocator() {
		return this.sampleLocator;
	}

	public void setSampleLocator(SampleLocator sampleLocator) {
		this.sampleLocator = sampleLocator;
	}

	@Column(name = "experimental_mass")
	public String getExperimentalMass() {
		return this.experimentalMass;
	}

	public void setExperimentalMass(String experimentalMass) {
		this.experimentalMass = experimentalMass;
	}

	@Column(name = "experimental_ip")
	public String getExperimentalIp() {
		return this.experimentalIp;
	}

	public void setExperimentalIp(String experimentalIp) {
		this.experimentalIp = experimentalIp;
	}

}
