package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.*;

/**
 * StudyContacts generated by hbm2java
 */
@Entity
@Table(name = "study_contacts", schema = "public")
public class StudyContacts implements java.io.Serializable {

	private int id;
	private Contact contact;
	private Study study;

	public StudyContacts() {
	}

	public StudyContacts(Contact contact, Study study) {
		this.contact = contact;
		this.study = study;
	}

	public StudyContacts(int id, Contact contact, Study study) {
		this.id = id;
		this.contact = contact;
		this.study = study;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "study_contacts_generator")
	@SequenceGenerator(name = "study_contacts_generator", sequenceName = "study_contacts_id_seq", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact", nullable = false)
	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "study", nullable = false)
	public Study getStudy() {
		return this.study;
	}

	public void setStudy(Study study) {
		this.study = study;
	}

}
