package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Study generated by hbm2java
 */
@Entity
@Table(name = "study", schema = "public", uniqueConstraints = { @UniqueConstraint(columnNames = "nomenclature_title"),
		@UniqueConstraint(columnNames = "title") })
public class Study implements java.io.Serializable {

	private int id;
	private Actor actor;
	private Project project;
	private String title;
	private String nomenclatureTitle;
	private String longTitle;
	private String description;
	private String identificationType;
	private String contractualFrame;
	private Boolean billed;
	private Date creationDate;
	private Date closingDate;
	private Date estimatedClosingDate;
	private String status;
	private Boolean confidential;
	private Set<Actor> actors = new HashSet<Actor>(0);
	private Set<StudyContacts> studyContactses = new HashSet<StudyContacts>(0);
	private Set<Sample> samples = new HashSet<Sample>(0);
	private Set<SeparationResult> separationResults = new HashSet<SeparationResult>(0);

	private String comment;

	public Study() {
	}

	public Study(int id, Actor actor, String title, String nomenclatureTitle, Date creationDate,
			String status, String comment) {
		this.id = id;
		this.actor = actor;
		this.title = title;
		this.nomenclatureTitle = nomenclatureTitle;
		this.creationDate = creationDate;
		this.status = status;
		this.comment = comment;
	}

	public Study(Actor actor, Project project, String title, String nomenclatureTitle,
				 String longTitle, String description, String identificationType,
				 String contractualFrame, Boolean billed, Date creationDate, Date closingDate,
				 Date estimatedClosingDate, String status, Boolean confidential, Set<Actor> actors,
				 Set<StudyContacts> studyContactses, Set<Sample> samples, Set<SeparationResult> separationResults, String comment) {
		this.actor = actor;
		this.project = project;
		this.title = title;
		this.nomenclatureTitle = nomenclatureTitle;
		this.longTitle = longTitle;
		this.description = description;
		this.identificationType = identificationType;
		this.contractualFrame = contractualFrame;
		this.billed = billed;
		this.creationDate = creationDate;
		this.closingDate = closingDate;
		this.estimatedClosingDate = estimatedClosingDate;
		this.status = status;
		this.confidential = confidential;
		this.actors = actors;
		this.studyContactses = studyContactses;
		this.samples = samples;
		this.separationResults = separationResults;
		this.comment = comment;
	}


	public Study(int id, Actor actor, Project project, String title, String nomenclatureTitle,
			String longTitle, String description, String identificationType,
			String contractualFrame, Boolean billed, Date creationDate, Date closingDate,
				 Date estimatedClosingDate, String status, Boolean confidential, Set<Actor> actors,
			Set<StudyContacts> studyContactses, Set<Sample> samples, Set<SeparationResult> separationResults, String comment) {
		this.id = id;
		this.actor = actor;
		this.project = project;
		this.title = title;
		this.nomenclatureTitle = nomenclatureTitle;
		this.longTitle = longTitle;
		this.description = description;
		this.identificationType = identificationType;
		this.contractualFrame = contractualFrame;
		this.billed = billed;
		this.creationDate = creationDate;
		this.closingDate = closingDate;
		this.estimatedClosingDate = estimatedClosingDate;
		this.status = status;
		this.confidential = confidential;
		this.actors = actors;
		this.studyContactses = studyContactses;
		this.samples = samples;
		this.separationResults = separationResults;
		this.comment = comment;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "study_generator")
	@SequenceGenerator(name = "study_generator", sequenceName = "study_id_seq", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "responsible", nullable = false)
	public Actor getActor() {
		return this.actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "title", unique = true, nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "nomenclature_title", unique = true, nullable = false, length = 10)
	public String getNomenclatureTitle() {
		return this.nomenclatureTitle;
	}

	public void setNomenclatureTitle(String nomenclatureTitle) {
		this.nomenclatureTitle = nomenclatureTitle;
	}

	@Column(name = "long_title")
	public String getLongTitle() {
		return this.longTitle;
	}

	public void setLongTitle(String longTitle) {
		this.longTitle = longTitle;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "identification_type")
	public String getIdentificationType() {
		return this.identificationType;
	}

	public void setIdentificationType(String identificationType) {
		this.identificationType = identificationType;
	}

	@Column(name = "contractual_frame")
	public String getContractualFrame() {
		return this.contractualFrame;
	}

	public void setContractualFrame(String contractualFrame) {
		this.contractualFrame = contractualFrame;
	}

	@Column(name = "billed")
	public Boolean getBilled() {
		return this.billed;
	}

	public void setBilled(Boolean billed) {
		this.billed = billed;
	}

	@Column(name = "creation_date", nullable = false)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "closing_date")
	public Date getClosingDate() {
		return this.closingDate;
	}

	public void setClosingDate(Date closingDate) {
		this.closingDate = closingDate;
	}

	@Column(name = "estimated_closing_date")
	public Date getEstimatedClosingDate() {
		return this.estimatedClosingDate;
	}

	public void setEstimatedClosingDate(Date estimatedClosingDate) {
		this.estimatedClosingDate = estimatedClosingDate;
	}

	@Column(name = "status", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "confidential")
	public Boolean getConfidential() {
		return this.confidential;
	}

	public void setConfidential(Boolean confidential) {
		this.confidential = confidential;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "studies_actors", schema = "public", joinColumns = {
			@JoinColumn(name = "study_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "actor_id", nullable = false, updatable = false) })
	public Set<Actor> getActors() {
		return this.actors;
	}

	public void setActors(Set<Actor> actors) {
		this.actors = actors;
	}

	public void addActor(Actor a) {
		this.actors.add(a);
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "study")
	public Set<StudyContacts> getStudyContactses() {
		return this.studyContactses;
	}

	public void setStudyContactses(Set<StudyContacts> studyContactses) {
		this.studyContactses = studyContactses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "study")
	public Set<Sample> getSamples() {
		return this.samples;
	}

	public void setSamples(Set<Sample> samples) {
		this.samples = samples;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "samples_share", schema = "public", joinColumns = {
			@JoinColumn(name = "study", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "separation_result", nullable = false, updatable = false) })
	public Set<SeparationResult> getSeparationResults() {
		return this.separationResults;
	}

	public void setSeparationResults(Set<SeparationResult> separationResults) {
		this.separationResults = separationResults;
	}

	@Column(name = "comment", nullable = true)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
