package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "tag", schema = "public")
public class Tag implements java.io.Serializable {

	private String name;
	private String label;
	private Set<FileTags> fileTagses = new HashSet<FileTags>(0);

	public Tag() {
	}

	public Tag(String name, String label) {
		this.name = name;
		this.label = label;
	}

	public Tag(String name, String label, Set<FileTags> fileTagses) {
		this.name = name;
		this.label = label;
		this.fileTagses = fileTagses;
	}

	@Id

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "label", nullable = false)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tag")
	public Set<FileTags> getFileTagses() {
		return this.fileTagses;
	}

	public void setFileTagses(Set<FileTags> fileTagses) {
		this.fileTagses = fileTagses;
	}

}
