package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TextDescriptionReference generated by hbm2java
 */
@Entity
@Table(name = "text_description_reference", schema = "public")
public class TextDescriptionReference implements java.io.Serializable {

	private TextDescriptionReferenceId id;

	public TextDescriptionReference() {
	}

	public TextDescriptionReference(TextDescriptionReferenceId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "description", column = @Column(name = "description")) })
	public TextDescriptionReferenceId getId() {
		return this.id;
	}

	public void setId(TextDescriptionReferenceId id) {
		this.id = id;
	}

}
