package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TextDescriptionReferenceId generated by hbm2java
 */
@Embeddable
public class TextDescriptionReferenceId implements java.io.Serializable {

	private Integer id;
	private String description;

	public TextDescriptionReferenceId() {
	}

	public TextDescriptionReferenceId(Integer id, String description) {
		this.id = id;
		this.description = description;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TextDescriptionReferenceId))
			return false;
		TextDescriptionReferenceId castOther = (TextDescriptionReferenceId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		return result;
	}

}
