package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TextDescription generated by hbm2java
 */
@Entity
@Table(name = "text_description", schema = "public")
public class TextDescription implements java.io.Serializable {

	private int id;
	private Reference reference;
	private String description;

	public TextDescription() {
	}

	public TextDescription(Reference reference, String description) {
		this.reference = reference;
		this.description = description;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.TextDescriptionIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "reference"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.TextDescriptionIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Reference getReference() {
		return this.reference;
	}

	public void setReference(Reference reference) {
		this.reference = reference;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
