package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Transfer generated by hbm2java
 */
@Entity
@Table(name = "transfer", schema = "public")
public class Transfer implements java.io.Serializable {

	private int id;
	private Actor actor;
	private ProtocolApplication protocolApplication;
	private Support supportByStartSupport;
	private Support supportByEndSupport;
	private String date;
	private String comment;

	public Transfer() {
	}

	public Transfer(int id, ProtocolApplication protocolApplication, Support supportByStartSupport,
			Support supportByEndSupport) {
		this.id = id;
		this.protocolApplication = protocolApplication;
		this.supportByStartSupport = supportByStartSupport;
		this.supportByEndSupport = supportByEndSupport;
	}

	public Transfer(int id, Actor actor, ProtocolApplication protocolApplication, Support supportByStartSupport,
			Support supportByEndSupport, String date, String comment) {
		this.id = id;
		this.actor = actor;
		this.protocolApplication = protocolApplication;
		this.supportByStartSupport = supportByStartSupport;
		this.supportByEndSupport = supportByEndSupport;
		this.date = date;
		this.comment = comment;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "actor")
	public Actor getActor() {
		return this.actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "protocol_application", nullable = false)
	public ProtocolApplication getProtocolApplication() {
		return this.protocolApplication;
	}

	public void setProtocolApplication(ProtocolApplication protocolApplication) {
		this.protocolApplication = protocolApplication;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "start_support", nullable = false)
	public Support getSupportByStartSupport() {
		return this.supportByStartSupport;
	}

	public void setSupportByStartSupport(Support supportByStartSupport) {
		this.supportByStartSupport = supportByStartSupport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "end_support", nullable = false)
	public Support getSupportByEndSupport() {
		return this.supportByEndSupport;
	}

	public void setSupportByEndSupport(Support supportByEndSupport) {
		this.supportByEndSupport = supportByEndSupport;
	}

	@Column(name = "date")
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
