package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Treatments generated by hbm2java
 */
@Entity
@Table(name = "treatments", schema = "public")
public class Treatments implements java.io.Serializable {

	private int id;
	private Protocol protocol;
	private String comment;
	private Set<TreatmentsApplication> treatmentsApplications = new HashSet<TreatmentsApplication>(0);
	private Set<Sample> samples = new HashSet<Sample>(0);

	public Treatments() {
	}

	public Treatments(int id) {
		this.id = id;
	}

	public Treatments(Protocol protocol, String comment,
					  Set<TreatmentsApplication> treatmentsApplications, Set<Sample> samples) {
		this.protocol = protocol;
		this.comment = comment;
		this.treatmentsApplications = treatmentsApplications;
		this.samples = samples;
	}

	public Treatments(int id, Protocol protocol, String comment,
			Set<TreatmentsApplication> treatmentsApplications/*, Set<Sample> samples*/) {
		this.id = id;
		this.protocol = protocol;
		this.comment = comment;
		this.treatmentsApplications = treatmentsApplications;
		this.samples = samples;
	}


	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "treatments_generator")
	@SequenceGenerator(name = "treatments_generator", sequenceName = "treatments_id_seq", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "protocol")
	public Protocol getProtocol() {
		return this.protocol;
	}

	public void setProtocol(Protocol protocol) {
		this.protocol = protocol;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "treatments")
	public Set<TreatmentsApplication> getTreatmentsApplications() {
		return this.treatmentsApplications;
	}

	public void setTreatmentsApplications(Set<TreatmentsApplication> treatmentsApplications) {
		this.treatmentsApplications = treatmentsApplications;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "treatments")
	public Set<Sample> getSamples() {
		return this.samples;
	}

	public void setSamples(Set<Sample> samples) {
		this.samples = samples;
	}

}
