package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TubeSupportId generated by hbm2java
 */
@Embeddable
public class TubeSupportId implements java.io.Serializable {

	private Integer id;
	private String sample;
	private Integer supportSeqRank;

	public TubeSupportId() {
	}

	public TubeSupportId(Integer id, String sample, Integer supportSeqRank) {
		this.id = id;
		this.sample = sample;
		this.supportSeqRank = supportSeqRank;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sample")
	public String getSample() {
		return this.sample;
	}

	public void setSample(String sample) {
		this.sample = sample;
	}

	@Column(name = "support_seq_rank")
	public Integer getSupportSeqRank() {
		return this.supportSeqRank;
	}

	public void setSupportSeqRank(Integer supportSeqRank) {
		this.supportSeqRank = supportSeqRank;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TubeSupportId))
			return false;
		TubeSupportId castOther = (TubeSupportId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getSample() == castOther.getSample()) || (this.getSample() != null
						&& castOther.getSample() != null && this.getSample().equals(castOther.getSample())))
				&& ((this.getSupportSeqRank() == castOther.getSupportSeqRank())
						|| (this.getSupportSeqRank() != null && castOther.getSupportSeqRank() != null
								&& this.getSupportSeqRank().equals(castOther.getSupportSeqRank())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getSample() == null ? 0 : this.getSample().hashCode());
		result = 37 * result + (getSupportSeqRank() == null ? 0 : this.getSupportSeqRank().hashCode());
		return result;
	}

}
