package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.*;

/**
 * VirtualWell generated by hbm2java
 */
@Entity
@Table(name = "virtual_well", schema = "public")
public class VirtualWell implements java.io.Serializable {

	private int id;
	private RobotPlanning robotPlanning;
	private VirtualPlate virtualPlate;
	private Integer XCoord;
	private Integer YCoord;

	public VirtualWell() {
	}

	public VirtualWell(int id) {
		this.id = id;
	}

	public VirtualWell(RobotPlanning robotPlanning, VirtualPlate virtualPlate, Integer XCoord, Integer YCoord) {
		this.robotPlanning = robotPlanning;
		this.virtualPlate = virtualPlate;
		this.XCoord = XCoord;
		this.YCoord = YCoord;
	}

	public VirtualWell(int id, RobotPlanning robotPlanning, VirtualPlate virtualPlate, Integer XCoord, Integer YCoord) {
		this.id = id;
		this.robotPlanning = robotPlanning;
		this.virtualPlate = virtualPlate;
		this.XCoord = XCoord;
		this.YCoord = YCoord;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "virtual_well_generator")
	@SequenceGenerator(name = "virtual_well_generator", sequenceName = "virtual_well_id_seq", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}
	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "robot_planning")
	public RobotPlanning getRobotPlanning() {
		return this.robotPlanning;
	}

	public void setRobotPlanning(RobotPlanning robotPlanning) {
		this.robotPlanning = robotPlanning;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "virtual_plate")
	public VirtualPlate getVirtualPlate() {
		return this.virtualPlate;
	}

	public void setVirtualPlate(VirtualPlate virtualPlate) {
		this.virtualPlate = virtualPlate;
	}

	@Column(name = "x_coord")
	public Integer getXCoord() {
		return this.XCoord;
	}

	public void setXCoord(Integer XCoord) {
		this.XCoord = XCoord;
	}

	@Column(name = "y_coord")
	public Integer getYCoord() {
		return this.YCoord;
	}

	public void setYCoord(Integer YCoord) {
		this.YCoord = YCoord;
	}

}
