package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WellSupportId generated by hbm2java
 */
@Embeddable
public class WellSupportId implements java.io.Serializable {

	private Integer id;
	private String sample;
	private Integer supportSeqRank;
	private String plate;
	private Integer XCoord;
	private Integer YCoord;

	public WellSupportId() {
	}

	public WellSupportId(Integer id, String sample, Integer supportSeqRank, String plate, Integer XCoord,
			Integer YCoord) {
		this.id = id;
		this.sample = sample;
		this.supportSeqRank = supportSeqRank;
		this.plate = plate;
		this.XCoord = XCoord;
		this.YCoord = YCoord;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sample")
	public String getSample() {
		return this.sample;
	}

	public void setSample(String sample) {
		this.sample = sample;
	}

	@Column(name = "support_seq_rank")
	public Integer getSupportSeqRank() {
		return this.supportSeqRank;
	}

	public void setSupportSeqRank(Integer supportSeqRank) {
		this.supportSeqRank = supportSeqRank;
	}

	@Column(name = "plate")
	public String getPlate() {
		return this.plate;
	}

	public void setPlate(String plate) {
		this.plate = plate;
	}

	@Column(name = "x_coord")
	public Integer getXCoord() {
		return this.XCoord;
	}

	public void setXCoord(Integer XCoord) {
		this.XCoord = XCoord;
	}

	@Column(name = "y_coord")
	public Integer getYCoord() {
		return this.YCoord;
	}

	public void setYCoord(Integer YCoord) {
		this.YCoord = YCoord;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WellSupportId))
			return false;
		WellSupportId castOther = (WellSupportId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getSample() == castOther.getSample()) || (this.getSample() != null
						&& castOther.getSample() != null && this.getSample().equals(castOther.getSample())))
				&& ((this.getSupportSeqRank() == castOther.getSupportSeqRank())
						|| (this.getSupportSeqRank() != null && castOther.getSupportSeqRank() != null
								&& this.getSupportSeqRank().equals(castOther.getSupportSeqRank())))
				&& ((this.getPlate() == castOther.getPlate()) || (this.getPlate() != null
						&& castOther.getPlate() != null && this.getPlate().equals(castOther.getPlate())))
				&& ((this.getXCoord() == castOther.getXCoord()) || (this.getXCoord() != null
						&& castOther.getXCoord() != null && this.getXCoord().equals(castOther.getXCoord())))
				&& ((this.getYCoord() == castOther.getYCoord()) || (this.getYCoord() != null
						&& castOther.getYCoord() != null && this.getYCoord().equals(castOther.getYCoord())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getSample() == null ? 0 : this.getSample().hashCode());
		result = 37 * result + (getSupportSeqRank() == null ? 0 : this.getSupportSeqRank().hashCode());
		result = 37 * result + (getPlate() == null ? 0 : this.getPlate().hashCode());
		result = 37 * result + (getXCoord() == null ? 0 : this.getXCoord().hashCode());
		result = 37 * result + (getYCoord() == null ? 0 : this.getYCoord().hashCode());
		return result;
	}

}
