package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WellSupport generated by hbm2java
 */
@Entity
@Table(name = "well_support", schema = "public")
public class WellSupport implements java.io.Serializable {

	private WellSupportId id;

	public WellSupport() {
	}

	public WellSupport(WellSupportId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "sample", column = @Column(name = "sample")),
			@AttributeOverride(name = "supportSeqRank", column = @Column(name = "support_seq_rank")),
			@AttributeOverride(name = "plate", column = @Column(name = "plate")),
			@AttributeOverride(name = "XCoord", column = @Column(name = "x_coord")),
			@AttributeOverride(name = "YCoord", column = @Column(name = "y_coord")) })
	public WellSupportId getId() {
		return this.id;
	}

	public void setId(WellSupportId id) {
		this.id = id;
	}

}
