package fr.edyp.epims.database.entities;
// Generated 10 mai 2021 � 11:47:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Well generated by hbm2java
 */
@Entity
@Table(name = "well", schema = "public")
public class Well implements java.io.Serializable {

	private int id;
	private Plate plate;
	private Support support;
	private Integer XCoord;
	private Integer YCoord;

	public Well() {
	}

	public Well(Support support) {
		this.support = support;
	}

	public Well(Plate plate, Support support, Integer XCoord, Integer YCoord) {
		this.plate = plate;
		this.support = support;
		this.XCoord = XCoord;
		this.YCoord = YCoord;
	}

	@GenericGenerator(name = "org.o7planning.generateentities.WellIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "support"))
	@Id
	@GeneratedValue(generator = "org.o7planning.generateentities.WellIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plate")
	public Plate getPlate() {
		return this.plate;
	}

	public void setPlate(Plate plate) {
		this.plate = plate;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Support getSupport() {
		return this.support;
	}

	public void setSupport(Support support) {
		this.support = support;
	}

	@Column(name = "x_coord")
	public Integer getXCoord() {
		return this.XCoord;
	}

	public void setXCoord(Integer XCoord) {
		this.XCoord = XCoord;
	}

	@Column(name = "y_coord")
	public Integer getYCoord() {
		return this.YCoord;
	}

	public void setYCoord(Integer YCoord) {
		this.YCoord = YCoord;
	}

}
